### ISSUE TITLE
Could not build Objective-C module 'CSwiftyCommonCrypto'

### ISSUE THREAD

**Issue by Hans-Fredrik** [Soneso/stellar-ios-mac-sdk#1]
Hi,
I am trying to build the SDK, but having issues with the module **CSwiftyCommonCrypto**.

Following errors occur during build:
- Header '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/CommonCrypto/CommonHMAC.h' not found

- Could not build Objective-C module 'CSwiftyCommonCrypto'

Is it necessary to manually handle CommonCrypto in the project ?

**Comment by chelemen-razvan** [comment]
Hello,

You are trying to build it for iOS? What xcode version are you using?

**Comment by Hans-Fredrik** [comment]
I'm currently building with Xcode Version 9.2 (9C40b)

**Comment by Hans-Fredrik** [comment]
Ops, my bad. Building fine now, the correct path for me is:  "/Applications/Xcode .app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/CommonCrypto/CommonHMAC.h"

Well there is a issue on this now, otherwise it could be good to have this as part of the documentation. Thank you for the quick support @chelemen-razvan  🤙🏻
