### ISSUE TITLE
Could not decode operation

### ISSUE THREAD

**Issue by ChangLongYuOne** [Soneso/stellar-ios-mac-sdk#101]
Operations中 包含 ManageDataOperation 时 Could not decode operation

**Comment by ChangLongYuOne** [comment]
例如transactionHash：d9380ae2861219d70ef8ccf3326fded0bf4cc59a3b6c17ab087b4f0f959dfb68

**Comment by christian-rogobete** [comment]
Thank you @ChangLongYuOne for reporting this. It is fixed in [release 1.9.4](https://github.com/Soneso/stellar-ios-mac-sdk/releases/tag/1.9.4)
