### ISSUE TITLE
Error Compiling Code

### ISSUE THREAD

**Issue by atulpatilbsetxt** [Soneso/stellar-ios-mac-sdk#11]
After update from cocoapod 
![screen shot 2018-05-09 at 6 10 35 pm](https://user-images.githubusercontent.com/34539288/39815017-575d5054-53b4-11e8-8260-9a8073010545.png)

**Comment by chelemen-razvan** [comment]
The library supports swift 4.1. If you cannot update your XCode and use swift 4.1 you'll have to use an older commit like e6a4b117443828beb09bd4fb18446716a5c0d2d0

**Comment by atulpatilbsetxt** [comment]
ok thanks @chelemen-razvan
