### ISSUE TITLE
Issues with Protocol 15 operations support v1.9.5

### ISSUE THREAD

**Issue by let-it-snow** [Soneso/stellar-ios-mac-sdk#110]
We are using Stellar SDK to display relevant transaction and operation details among other things in the app.

We are looking to add the full support for Protocol 15 operations for users to be able to view the relevant details and sign transactions as they wish.

We’ve encountered a few issues, hopefully you’ll be able to assist.

**1. Source account requirement for beginSponsoringFutureReserves**

We are using the ‘fromXDR(operationXDR:OperationXDR)’ method to get transaction and operation details.

‘beginSponsoringFutureReserves(let data)’ handler requires for the source account id of the operation to be present to return the details.

From our understanding, the source account id should be optional here as it is not required if the source account is set at the transaction level.

Code reference:
```       
case .beginSponsoringFutureReserves(let data):
          if let sponsoringAccountId = mSourceAccountId {
            return try BeginSponsoringFutureReservesOperation(fromXDR: data, sponsoringAccountId:sponsoringAccountId)
          } else {
            throw StellarSDKError.invalidArgument(message: "Missing source account id for BeginSponsoringFutureReservesOperation")
          } 
```
Are we missing something here? It works as expected if we remove the requirement as follows:
```
       case .beginSponsoringFutureReserves(let data):
             return try BeginSponsoringFutureReservesOperation(fromXDR: data, sponsoringAccountId: data.sponsoredId.accountId)
```

**2. revokeSponsorship case is missing**

It looks like there is no code to handle the revokeSponsorship operation case in the ‘fromXDR(operationXDR:OperationXDR)’ method.

So we can’t obtain the details for this operation type.

Is there a reason for this?

We’ve attempted to add this case ourselves similar to other operation types as follows:

```
        case .revokeSponsorship(let data):
          return try RevokeSponsorshipOperation(fromXDR: data, sourceAccountId: mSourceAccountId)
```

This resulted in the next issue:

**revokeSponsorship details issue**

‘LedgerKeyXDR’ is defined for the ‘revokeSponsorship’ operation:

```
public class RevokeSponsorshipOperation:Operation {
    public let ledgerKey:LedgerKeyXDR?
    public let signerAccountId:String?
    public let signerKey:SignerKeyXDR?
```
```
public enum LedgerKeyXDR: XDRCodable {
    case account (LedgerKeyAccountXDR)
    case trustline (LedgerKeyTrustLineXDR)
    case offer (LedgerKeyOfferXDR)
    case data (LedgerKeyDataXDR)
    case claimableBalance (ClaimableBalanceIDXDR)
```
```
public struct LedgerKeyAccountXDR: XDRCodable {
    let accountID: PublicKey
```

We run into an issue when attempting to parse and extract the operation details in ‘LedgerKeyXDR’ using the same logic we use for other operations.

For example, when we are looking to get the ‘data.accountID’ from ‘LedgerKeyAccountXDR’, the code throws an error as if it is not available (the option is not highlighted). Even though it is defined as highlighted above. 

It works for other operation types as expected.

**Comment by christian-rogobete** [comment]
Hello @let-it-snow, thank you for adding this issue. Can you please send me your xdr for testing?

**Comment by christian-rogobete** [comment]
fixed [here](https://github.com/Soneso/stellar-ios-mac-sdk/commit/dc8ad3586ccd6d7f614254b27510e38ba18a80ee). I will add this to the next release (next weekend)

**Comment by let-it-snow** [comment]
Hello @christian-rogobete 

Thanks for the quick fix.
Please see the XDR examples below. Can you please look at the `endSponsoringFutureReserves` case as well?

**The transaction source is the sponsoring account**

In this case, the source account is not set for the `beginSponsoringFutureReserves` operation. The transaction source account is the account sponsoring the trustline creation.

``AAAAAgAAAADcm14tIMFDRcMNOUw/gO/gtUDUOq+PXc4rZYZKJrdGegAAASwBB5+3AAAKgQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAEAAAAAByVce6q9GUrZL+M4E/i8ef6XvHGSW11PD6js609AWNBAAAAAEAAAAAclXHuqvRlK2S/jOBP4vHn+l7xxkltdTw+o7OtPQFjQQAAAAGAAAAAXlYTE0AAAAAIjbXcP4NPgFSGXXVz3rEhCtwldaxqddo0+mmMumZBr5//////////wAAAAEAAAAAclXHuqvRlK2S/jOBP4vHn+l7xxkltdTw+o7OtPQFjQQAAAARAAAAAAAAAAA=``

**The transaction source is the sponsored account**

In this case, the source account is not set for the `endSponsoringFutureReserves` operation. The transaction source account is the account that the trustline creation is being sponsored for. It seems like this case should be handled as well.

``AAAAAgAAAAByVce6q9GUrZL+M4E/i8ef6XvHGSW11PD6js609AWNBAAAASwBegt5AAAB+gAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABAAAAANybXi0gwUNFww05TD+A7+C1QNQ6r49dzitlhkomt0Z6AAAAEAAAAAByVce6q9GUrZL+M4E/i8ef6XvHGSW11PD6js609AWNBAAAAAAAAAAGAAAAAXlYTE0AAAAAIjbXcP4NPgFSGXXVz3rEhCtwldaxqddo0+mmMumZBr5//////////wAAAAAAAAARAAAAAAAAAAA=``

**revokeSponsorship operations**

Here is an example for revoking the sponsorship of the signer entry. It looked like this case was missing in the SDK.

``AAAAAgAAAADcm14tIMFDRcMNOUw/gO/gtUDUOq+PXc4rZYZKJrdGegAAAGQAAgzLAAAAGQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAEgAAAAEAAAAAclXHuqvRlK2S/jOBP4vHn+l7xxkltdTw+o7OtPQFjQQAAAAA1Z5EemLo84TPxjTSa20raJLBdRAjJReW1V2EgYYAzngAAAAAAAAAAA==``

**Comment by christian-rogobete** [comment]
Hello @let-it-snow,

thank you for your hint. You are right and I removed the requirement for `endSponsoringFutureReserves` op. A new release [1.9.7](https://github.com/Soneso/stellar-ios-mac-sdk/releases/tag/1.9.7) is now available.
