### ISSUE TITLE
Xcode 12.5 is not supported. 

### ISSUE THREAD

**Issue by madeofmoney** [Soneso/stellar-ios-mac-sdk#112]
Errors everywhere stemming from Generics.swift.

**Comment by madeofmoney** [comment]
```
@_specialize(exported: true, where T == Int)
```
"exported: true has no effect in _specialize attribute

**Comment by christian-rogobete** [comment]
Hello @madeofmoney,
this was added here https://github.com/Soneso/stellar-ios-mac-sdk/commit/07d5bab28d90a4f03f955ec8eeb5ffebde294503
do you have the newest release?

**Comment by madeofmoney** [comment]
Ah thanks for this needed to upgrade. Testing now!
