### ISSUE TITLE
Add streaming support for accounts, offers, trades, order books.

### ISSUE THREAD

**Issue by light-cloud** [Soneso/stellar-ios-mac-sdk#113]
You have already implemented streaming support for ledgers, transactions, operations, payments, and effects.

Can you, please, also add support of streaming for:

- Accounts
- Offers
- Trades
- Order Books?

It can be useful for implementing real-time trading features.

**Comment by light-cloud** [comment]
Hello @christian-rogobete

Did you have a chance to look at this issue?
Android SDK has this implemented which is very useful.

We are looking to use streaming to enhance the trading/market related features. It would be great to know if we should expect the support to be added to the SDK or if we should implement a solution on our end?

**Comment by christian-rogobete** [comment]
Hello @light-cloud thank you for adding this issue. I planned to add those next week. If you need them urgent, why not contribute by adding them the to the sdk and make a pull request?

**Comment by light-cloud** [comment]
@christian-rogobete thank you for the fast response. Sure, we will be glad to contribute. I can start shortly and will provide a pull request next week.

**Comment by christian-rogobete** [comment]
@light-cloud thank you for your contribution
