### ISSUE TITLE
Verify Podspec Version Matches - Build Phase Bug

### ISSUE THREAD

**Issue by cbaies-bc** [Soneso/stellar-ios-mac-sdk#114]
The "Verify Podspec Version Matches" Build Phase fails on newer versions of MacOS, due to a change in the `defaults` command it uses.

Currently, the script uses `defaults` to parse out the value of `CFBundleShortVersionString` from the `Info.plist` file. However, this behaviour has been changed on more recent versions, as can be found in the `man` page for `defaults`:

               WARNING: The defaults command will be changed in an upcoming
               major release to only operate on preferences domains. General
               plist manipulation utilities will be folded into a different
               command-line program.

This [issue](https://github.com/flutter/flutter/issues/37701) has also been caught in other projects, where they opted to using `plutil`. A nice approach to using this command can be found [here](https://stackoverflow.com/a/46160882).

The fix I implemented in the meantime is the following:

```bash
INFO_PLIST="${SRCROOT}/stellarsdk/Info.plist"
SDK_VERSION="$(plutil -extract CFBundleShortVersionString xml1 -o - $INFO_PLIST | sed -n "s/.*<string>\(.*\)<\/string>.*/\1/p")"
```

**Comment by christian-rogobete** [comment]
Hello @cbaies-bc, thank you for adding this issue. I will use your nice solution. Multumesc

**Comment by christian-rogobete** [comment]
added in [release 1.9.8](https://github.com/Soneso/stellar-ios-mac-sdk/releases/tag/1.9.8)
