### ISSUE TITLE
The issue with TransactionResultXDR parsing in Protocol 18.

### ISSUE THREAD

**Issue by let-it-snow** [Soneso/stellar-ios-mac-sdk#135]
When the Path Payment Strict Send operation goes through the LiquidityPool - SDK parses TransactionResultXDR object with incorrect data and amounts which are different from what we can see in the Stellar Laboratory.
Transaction Example:
hash: `c08aa6ddc85a45e61616e04169255b65ef8f18a1770cfd1f9d6ef06e1d9181b5`
result XDR: `AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAANAAAAAAAAAAMAAAACyIKYeT/PVZ525AbJ5qFGX2a3dmZTfkdTdS7+VC2nJOoAAAABVVNEAAAAAAC4yDllC4wc8MFpfq+TvoUU1t9hHysSWY8bznoIAStjLQAAAAADR2jEAAAAAVVTREMAAAAAV/4SZ1wTCkLfxCfFO2dNY/5NB5Bt4jYhkU9JgmGKlLMAAAAAALcbAAAAAAEAAAAAw+9uw8pDzN04gbAnRvqwDPvnSMfw9HFwY1rT9/MHluUAAAAAAAXsuQAAAAFSSU8AAAAAALjIOWULjBzwwWl+r5O+hRTW32EfKxJZjxvOeggBK2MtAAAAAAC2GBQAAAABVVNEAAAAAAC4yDllC4wc8MFpfq+TvoUU1t9hHysSWY8bznoIAStjLQAAAAADR2jEAAAAAQAAAADD727DykPM3TiBsCdG+rAM++dIx/D0cXBjWtP38weW5QAAAAAABfNUAAAAAAAAAAAT/GYZAAAAAVJJTwAAAAAAuMg5ZQuMHPDBaX6vk76FFNbfYR8rElmPG856CAErYy0AAAAAALYYFAAAAACN28YF+p1Z8/Ftgnc9+oJE2IrDjeHuSF+f1dAYXbHjwAAAAAAAAAAAE/xmGQAAAAA=`

When you try to parse the result XDR from Path Payment Strict Send operation, which consists only of Order Book offers - everything is fine and the object, parsed with SDK is similar to Stellar Laboratory. 
Transaction Example:
hash: `8f689a09759ca97669f7fd7e36a65fc3d425e78b0e43d8d193ed0d914b420ad4`
result XDR: `AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAANAAAAAAAAAAMAAAABAAAAAI3bxgX6nVnz8W2Cdz36gkTYisON4e5IX5/V0BhdsePAAAAAAAAF/OAAAAABekVUSAAAAADDduQAxHh96hdAUvmvXsG/9m0kpBY+OLwDdL/a5Tj7lwAAAAAHJw4AAAAAAnpVU0RDAAAAAAAAAAAAAADDduQAxHh96hdAUvmvXsG/9m0kpBY+OLwDdL/a5Tj7lwAAAAAF9eEAAAAAAQAAAACN28YF+p1Z8/Ftgnc9+oJE2IrDjeHuSF+f1dAYXbHjwAAAAAAABfzeAAAAAXpCVEMAAAAAw3bkAMR4feoXQFL5r17Bv/ZtJKQWPji8A3S/2uU4+5cAAAAADk4cAAAAAAF6RVRIAAAAAMN25ADEeH3qF0BS+a9ewb/2bSSkFj44vAN0v9rlOPuXAAAAAAcnDgAAAAABAAAAAI3bxgX6nVnz8W2Cdz36gkTYisON4e5IX5/V0BhdsePAAAAAAAAF/NsAAAACekFRVUEAAAAAAAAAAAAAAMN25ADEeH3qF0BS+a9ewb/2bSSkFj44vAN0v9rlOPuXAAAAAAX14QAAAAABekJUQwAAAADDduQAxHh96hdAUvmvXsG/9m0kpBY+OLwDdL/a5Tj7lwAAAAAOThwAAAAAAI1SYdUyLLYHFj5RkpytXEwR8y4PzrDyTx1+rYVXJkIfAAAAAnpBUVVBAAAAAAAAAAAAAADDduQAxHh96hdAUvmvXsG/9m0kpBY+OLwDdL/a5Tj7lwAAAAAF9eEAAAAAAA==`

**Comment by christian-rogobete** [comment]
Thank you for submitting this issue. I found the error and I fixed it in this commit:
https://github.com/Soneso/stellar-ios-mac-sdk/commit/0b2e9f6140c55a2931208bb5fe347cce0f317bd5

**Comment by christian-rogobete** [comment]
fixed in [release 2.0.7](https://github.com/Soneso/stellar-ios-mac-sdk/releases/tag/2.0.7)
