### ISSUE TITLE
Muxed accounts should now be enabled by default.

### ISSUE THREAD

**Issue by Shaptic** [Soneso/stellar-ios-mac-sdk#139]
Muxed accounts (introduced into the protocol in [CAP-27](https://stellar.org/protocol/cap-27) and defined in its string form in [SEP-23](https://stellar.org/protocol/sep-23)) **should now be supported by default**. Previously, we asked that they be hidden behind an opt-in feature flag; now, they should always be supported.

The following fields are muxed accounts and can thus be either a standard `G...` or a muxed `M...` address:

  * `FeeBumpTransaction.feeSource`
  * `Transaction.sourceAccount`
  * `Operation.sourceAccount`
  * `Payment.destination`
  * `PathPaymentStrictReceive.destination`
  * `PathPaymentStrictSend.destination`
  * `AccountMerge.destination`
  * `Clawback.from`

While the list above should be comprehensive, you can always refer to [the XDR](https://github.com/stellar/stellar-core/blob/master/src/xdr/Stellar-transaction.x) for an authoritative source of truth.

Refer to the following releases for reference implementations:

 - Go: [`horizonclient@v9.0.0`](https://github.com/stellar/go/releases/tag/horizonclient-v9.0.0)
 - JavaScript: [`stellar-base@v7.0.0`](https://github.com/stellar/js-stellar-base/releases/tag/v7.0.0) and [`stellar-sdk@v10.0.0`](https://github.com/stellar/js-stellar-sdk/releases/tag/v10.0.0)
 - Java: [`java-stellar-sdk@v0.31.0`](https://github.com/stellar/java-stellar-sdk/releases/tag/0.31.0)
 - Python: [`py-stellar-base@v7.0.0`](https://github.com/StellarCN/py-stellar-base/releases/tag/7.0.0)

Additional documentation is available in the [glossary](https://developers.stellar.org/docs/glossary/muxed-accounts/).

**Comment by christian-rogobete** [comment]
Thank you for adding this issue. In this SDK Muxed accounts are already supported by default.
