### ISSUE TITLE
Issue with OperationResultXDR parsing

### ISSUE THREAD

**Issue by let-it-snow** [Soneso/stellar-ios-mac-sdk#140]
```OperationResultXDR``` parsing crashes here: ```let code = OperationResultCode(rawValue: discriminant)!```

Please look at the XDR example below
```AAAAAgAAAAAzLZ8nl00dWGwmhZ41swmc14jvBRVZNf4HKJZC7Cn7rwADDUAB6XUMAAAIeQAAAAAAAAAAAAAAAgAAAAEAAAAAMy2fJ5dNHVhsJoWeNbMJnNeI7wUVWTX+ByiWQuwp+68AAAANAAAAAVVTRAAAAAAA6KYahh5gr2D4B3PgY0blxyy+Wdyt2jdgjVjvQlEdn9wAAAAAAAZhQgAAAAAzLZ8nl00dWGwmhZ41swmc14jvBRVZNf4HKJZC7Cn7rwAAAAAAAAAAABngLwAAAAEAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAEAAAAAMy2fJ5dNHVhsJoWeNbMJnNeI7wUVWTX+ByiWQuwp+68AAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAJbG9ic3RyLmNvAAAAAAAAAAAAAAAAAAAC7Cn7rwAAAEBtbQWhFE9e1z+uCEm/D54NYqSkQXL3kP+pgYYFmTiDNFCm0Bj4mljcPaANvqBGc1Kj/LoRWJh582FR5MAwGcIIAY1PewAAAEA0aWjOGDvgZ3vOreMwoHuuiapX9n4i79Lr3eZPXGmbZON97F46zEkjjqXavkp3TmvjAsEiOr++7hrdrnNXzhoG```

**Comment by christian-rogobete** [comment]
Hi @let-it-snow,

thank you for adding this issue. I tried to reproduce the crash, but no luck. Can you pls. send me your code?
You can find my test here: https://github.com/Soneso/stellar-ios-mac-sdk/commit/69b7cc1f00e060aa97f1c01f808539dfa4d16077

**Comment by christian-rogobete** [comment]
Thank you for the hint, I will check it.

**Comment by christian-rogobete** [comment]
Hi @let-it-snow, unfortunately I can still not reproduce it. I submitted your xdr with the sdk to the public net. Resulting transaction hash is: 295399fe8355eccdb66a8e893cbd9048e134309477777a495aea2e2b7c440ac7
There was no error. I also added a test case which parses the xdr data from the transaction (envelope_xdr, result_xdr and result_meta_xdr). See: https://github.com/Soneso/stellar-ios-mac-sdk/commit/71e64eaa60ec6a3b4204a1a1d93005374c6f1ffa

Can you please send me an xdr that can not be parsed resulting into the crash mentioned above?

Thx

**Comment by let-it-snow** [comment]
It was my fault, i used old sdk, after update to the latest one (2.0.9) everything works fine. sorry for disturbing.

**Comment by christian-rogobete** [comment]
No problem, thanks for adding the new PR
