### ISSUE TITLE
Claimable Balance ID changes after signing XDR with Claim Claimable Balance operation.

### ISSUE THREAD

**Issue by let-it-snow** [Soneso/stellar-ios-mac-sdk#142]
Balance ID of a claimable balance specified in the ‘Claim Claimable Balance’ operation changes after XDR with claimClaimableBalanceOp is signed. This happens when we get OperationXDR from Operation.

XDR before signing:
```AAAAAgAAAABgQUKgloqfjWKlxglkCYLs+7ZijoZgvVAbtwl7003XEwABhqACDNetAAAhQgAAAAAAAAAAAAAAAQAAAAAAAAAPAAAAAABxD+mmyQJJTIhTgpDBVsNJPSwfe5Fvxh3cb/O17iEgAAAAAAAAAAA=```

balanceId: ```AHEP6abJAklMiFOCkMFWw0k9LB97kW/GHdxv87XuISA=```

Operation XDR:
```AAAAAAAAAA8AAAAAcQ/ppskCSUyIU4KQwVbDST0sH3uRb8Yd3G/zte4hIAA=```

balanceId: ```cQ/ppskCSUyIU4KQwVbDST0sH3uRb8Yd3G/zte4hIAA=```

XDR after signing:
```AAAAAgAAAABgQUKgloqfjWKlxglkCYLs+7ZijoZgvVAbtwl7003XEwABhqACDNetAAAhTwAAAAAAAAAAAAAAAQAAAAAAAAAPAAAAAHEP6abJAklMiFOCkMFWw0k9LB97kW/GHdxv87XuISAAAAAAAAAAAAHTTdcTAAAAQIj4E/PilCc7c1IXiik3Mm7934HexEMb5KAxgpxgv7tPExR5F67yWv0kjjIheJiE9HLnRwdxFwb3zA9loa1//wg=```

balanceId: ```cQ/ppskCSUyIU4KQwVbDST0sH3uRb8Yd3G/zte4hIAA=```

**Comment by let-it-snow** [comment]
Hello @christian-rogobete 
Could you please take a look at the issue we’ve created? Let us know if you need any more details or any help with reproducing this issue. It would be great to have this fixed. Thanks

**Comment by christian-rogobete** [comment]
Hello @let-it-snow, thank you for reporting this issue. I can reproduce it and I will try to fix it at the end of this week.

**Comment by christian-rogobete** [comment]
fixed in release [2.1.0](https://github.com/Soneso/stellar-ios-mac-sdk/releases/tag/2.1.0)
