### ISSUE TITLE
SEP-12 Support

### ISSUE THREAD

**Issue by light-cloud** [Soneso/stellar-ios-mac-sdk#145]
Can you add support for SEP-12?
https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0012.md

[GET /customer](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0012.md#customer-get): Check the status of a customers info

Thanks.

**Comment by christian-rogobete** [comment]
Hi @light-cloud, yes, I guess we can add it in May.

**Comment by christian-rogobete** [comment]
resolved in [release 2.3.6](https://github.com/Soneso/stellar-ios-mac-sdk/releases/tag/2.3.6)
