### ISSUE TITLE
Soroban Preview 10 Support

### ISSUE THREAD

**Issue by let-it-snow** [Soneso/stellar-ios-mac-sdk#146]
Hello.
Can you add support for Soroban Preview 10?
https://soroban.stellar.org/docs/reference/releases#preview-10-july-13-2023

```SCContractExecutableXDR``` init crashes here: ```let type = SCContractCodeType(rawValue: discriminant)!``` when trying to work with transaction XDRs on the latest Preview.

Please look at the XDR example below
```AAAAAgAAAAC73Q6G1iDn49DXQGPC0phEfJm9JNO21EGLNinWxRsQ4QAAJxAAALGOAAAABQAAAAEAAAAAAAAAAAAAAABkuP5dAAAAAAAAAAEAAAAAAAAAGAAAAAEAAAABAAAAAkxvYnN0clRva2VuMQAAAAC8deNJuq+L0pu+Be27UUtPwmzEtrwAzOMvgF8zG9B7CAAAAAEAAAAAAAAAAAAAAAA=```

Thanks.

**Comment by christian-rogobete** [comment]
Hello, yes, I am going to add it at the beginning of next week.

**Comment by christian-rogobete** [comment]
Done in [release 2.3.9](https://github.com/Soneso/stellar-ios-mac-sdk/releases/tag/2.3.9)
