### ISSUE TITLE
Soroban simulateTransaction method

### ISSUE THREAD

**Issue by let-it-snow** [Soneso/stellar-ios-mac-sdk#150]
Hello.
simulateTransaction method doesn’t work correctly with the latest version of SDK. Auth array is empty. 
Please look at the XDR example below

Initial XDR:
```AAAAAgAAAABiaYjnyXPQ+fKgN/L9DQUBjV5pY/lpzc4C9LwETQd90wAAAGQACjNnAAAABwAAAAEAAAAAAAAAAAAAAABk8JfDAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAAFAAAAEgAAAAF9wezfkzUZn8mRjb4Mcyzh0RRqqPKcycNgr8anR66U3wAAAA8AAAAIdHJhbnNmZXIAAAASAAAAAAAAAABiaYjnyXPQ+fKgN/L9DQUBjV5pY/lpzc4C9LwETQd90wAAABIAAAAAAAAAAKyRBFaSPyfLm4NniM4yoy59W3ZO9CLDVw7ahB0HcjIUAAAACgAAAAAAAAAAAAAAAB3NZQAAAAAAAAAAAAAAAAA=```

XDR after simulation: 
```AAAAAgAAAABiaYjnyXPQ+fKgN/L9DQUBjV5pY/lpzc4C9LwETQd90wABGHQACjNnAAAABwAAAAEAAAAAAAAAAAAAAABk8JfDAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAAFAAAAEgAAAAF9wezfkzUZn8mRjb4Mcyzh0RRqqPKcycNgr8anR66U3wAAAA8AAAAIdHJhbnNmZXIAAAASAAAAAAAAAABiaYjnyXPQ+fKgN/L9DQUBjV5pY/lpzc4C9LwETQd90wAAABIAAAAAAAAAAKyRBFaSPyfLm4NniM4yoy59W3ZO9CLDVw7ahB0HcjIUAAAACgAAAAAAAAAAAAAAAB3NZQAAAAAAAAAAAQAAAAAAAAABAAAABgAAAAF9wezfkzUZn8mRjb4Mcyzh0RRqqPKcycNgr8anR66U3wAAABQAAAABAAAAAAAAAAIAAAAAAAAAAGJpiOfJc9D58qA38v0NBQGNXmlj+WnNzgL0vARNB33TAAAAAAAAAACskQRWkj8ny5uDZ4jOMqMufVt2TvQiw1cO2oQdB3IyFAAENW8AAAKkAAABcAAABNwAAAAAAAAA8wAAAAA=```

Correct XDR after simulation for example: 
```AAAAAgAAAABiaYjnyXPQ+fKgN/L9DQUBjV5pY/lpzc4C9LwETQd90wABGHQACjNnAAAABwAAAAEAAAAAAAAAAAAAAABk8JfDAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAAFAAAAEgAAAAF9wezfkzUZn8mRjb4Mcyzh0RRqqPKcycNgr8anR66U3wAAAA8AAAAIdHJhbnNmZXIAAAASAAAAAAAAAABiaYjnyXPQ+fKgN/L9DQUBjV5pY/lpzc4C9LwETQd90wAAABIAAAAAAAAAAKyRBFaSPyfLm4NniM4yoy59W3ZO9CLDVw7ahB0HcjIUAAAACgAAAAAAAAAAAAAAAB3NZQAAAAABAAAAAAAAAAAAAAABfcHs35M1GZ/JkY2+DHMs4dEUaqjynMnDYK/Gp0eulN8AAAAIdHJhbnNmZXIAAAADAAAAEgAAAAAAAAAAYmmI58lz0PnyoDfy/Q0FAY1eaWP5ac3OAvS8BE0HfdMAAAASAAAAAAAAAACskQRWkj8ny5uDZ4jOMqMufVt2TvQiw1cO2oQdB3IyFAAAAAoAAAAAAAAAAAAAAAAdzWUAAAAAAAAAAAEAAAAAAAAAAQAAAAYAAAABfcHs35M1GZ/JkY2+DHMs4dEUaqjynMnDYK/Gp0eulN8AAAAUAAAAAQAAAAAAAAACAAAAAAAAAABiaYjnyXPQ+fKgN/L9DQUBjV5pY/lpzc4C9LwETQd90wAAAAAAAAAArJEEVpI/J8ubg2eIzjKjLn1bdk70IsNXDtqEHQdyMhQABDVvAAACpAAAAXAAAATcAAAAAAAAAPMAAAAA```

Thanks.

**Comment by christian-rogobete** [comment]
Hello @let-it-snow,

have you checked the [doc](https://github.com/Soneso/stellar-ios-mac-sdk/blob/master/soroban.md#soroban-authorization) and the test cases for soroban? E.g. the [auth test](https://github.com/Soneso/stellar-ios-mac-sdk/blob/master/stellarsdk/stellarsdkTests/soroban/SorobanAuthTest.swift)

Thanks

**Comment by let-it-snow** [comment]
Hello @christian-rogobete 
Thanks.

**Comment by christian-rogobete** [comment]
You are welcome @let-it-snow!
