### ISSUE TITLE
Upcoming third-party SDK requirements

### ISSUE THREAD

**Issue by light-cloud** [Soneso/stellar-ios-mac-sdk#158]
Hi!

Can you, please, check if SDK requires any updates to comply with Apple's new requirements concerning the Privacy Manifest file. Starting in May, it appears that SDKs will need to include a Privacy Manifest file.

Could you please confirm if changes are needed for the SDK? For instance, I noticed that usage of UserDefaults must be declared in this file, as detailed here: [Describing Use of Required Reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401).

You can find more about these requirements on Apple's official support page: [Apple Developer Third-Party SDK Requirements](https://developer.apple.com/support/third-party-SDK-requirements/), but I am not sure if it is required for all, because they also provide a list of popular SDKs. So, maybe, it is only needed for them.

Thank you for checking this and looking forward to your guidance.

**Comment by christian-rogobete** [comment]
Hi @light-cloud, I removed the usage of UserDefaults in this release: 
https://github.com/Soneso/stellar-ios-mac-sdk/releases/tag/2.6.0
I think that this will resolve the issue as the SDK does not use any api described in the apple docs.
Thank you for adding this issue.
