### ISSUE TITLE
Сhecksum issue in Mnemonic.create

### ISSUE THREAD

**Issue by GoodX-Network** [Soneso/stellar-ios-mac-sdk#16]
Function Mnemonic.create uses 8-bit checksum (for 24 words seed) during mnemonic words seed generation. 
But neither Wallet.createKeyPair nor Mnemonic.createSeed are checking checksum.

**Comment by chelemen-razvan** [comment]
I am not sure what you mean. Do you refer to the fact that  Wallet.createKeyPair does not check if the mnemonic is valid or not?

**Comment by GoodX-Network** [comment]
Exactly, you right. When we create the key-pairs, you are not validating the mnemonic words

**Comment by chelemen-razvan** [comment]
Well I guess this could be an improvement, right now its the responsibility of the developer/user of the library to make sure that the mnemonic is valid.
