### ISSUE TITLE
Issue with parsing transaction XDR into the transaction object and back

### ISSUE THREAD

**Issue by let-it-snow** [Soneso/stellar-ios-mac-sdk#160]
Hi!
The parsing of the XDR string into the Transaction object and back doesn't work correctly.

1. Get Transaction from XDR (Transaction(envelopeXdr: xdr))
2. Sign transaction (transaction.sign(keyPair: keyPair, network: .public))
3. Get XDR from Transaction (transaction.encodedEnvelope())

Please look at the XDR example below

Initial XDR:
```AAAAAgAAAAAUUMZa5TbyN9cbCX4kletMEEZayUvXcEXaV89yUJD4wQAGu7MBa2KiAABDsgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAABl5iPhP6n9Isibt/1Nfhty4VAS/cIJd/2f0za4fhJqaQAAAAEc3dhcAAAAAQAAAASAAAAAAAAAAAUUMZa5TbyN9cbCX4kletMEEZayUvXcEXaV89yUJD4wQAAABAAAAABAAAAAQAAABEAAAABAAAAAwAAAA8AAAAJYXNrX2Fzc2V0AAAAAAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAAA8AAAAUYXNrX2Fzc2V0X21pbl9hbW91bnQAAAABAAAADwAAAAtvZmZlcl9hc3NldAAAAAASAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAABgAAAAAAAABkAAAACgAAAAAAAAAAAAAAAAAehIAAAAABAAAAAAAAAAAAAAABl5iPhP6n9Isibt/1Nfhty4VAS/cIJd/2f0za4fhJqaQAAAAEc3dhcAAAAAQAAAASAAAAAAAAAAAUUMZa5TbyN9cbCX4kletMEEZayUvXcEXaV89yUJD4wQAAABAAAAABAAAAAQAAABEAAAABAAAAAwAAAA8AAAAJYXNrX2Fzc2V0AAAAAAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAAA8AAAAUYXNrX2Fzc2V0X21pbl9hbW91bnQAAAABAAAADwAAAAtvZmZlcl9hc3NldAAAAAASAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAABgAAAAAAAABkAAAACgAAAAAAAAAAAAAAAAAehIAAAAABAAAAAAAAAAFOKMq33nPyGnLDFPIU2W2jUUiShHdABJPjEW7pvCVp4AAAAARzd2FwAAAABQAAABIAAAAAAAAAABRQxlrlNvI31xsJfiSV60wQRlrJS9dwRdpXz3JQkPjBAAAAEgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAAAoAAAAAAAAAAAAAAAAAHoSAAAAAAQAAAAYAAAAAAAAAZAAAAAEAAAAAAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAACHRyYW5zZmVyAAAAAwAAABIAAAAAAAAAABRQxlrlNvI31xsJfiSV60wQRlrJS9dwRdpXz3JQkPjBAAAAEgAAAAFOKMq33nPyGnLDFPIU2W2jUUiShHdABJPjEW7pvCVp4AAAAAoAAAAAAAAAAAAAAAAAHoSAAAAAAAAAAAEAAAAAAAAACgAAAAYAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAAUAAAAAQAAAAYAAAABTijKt95z8hpywxTyFNlto1FIkoR3QAST4xFu6bwlaeAAAAAPAAAABkNPTkZJRwAAAAAAAQAAAAYAAAABTijKt95z8hpywxTyFNlto1FIkoR3QAST4xFu6bwlaeAAAAAUAAAAAQAAAAYAAAABeSqCyQenKLXJz+2gWLbnh9rHmWFyoaFXIhuRZIbIk5EAAAARAAAAAQAAAAIAAAAPAAAAB3Rva2VuX2EAAAAAEgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAAA8AAAAHdG9rZW5fYgAAAAASAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAAQAAAAYAAAABeSqCyQenKLXJz+2gWLbnh9rHmWFyoaFXIhuRZIbIk5EAAAAUAAAAAQAAAAYAAAABl5iPhP6n9Isibt/1Nfhty4VAS/cIJd/2f0za4fhJqaQAAAAUAAAAAQAAAAYAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAAUAAAAAQAAAAdgMyuhKAHtplh06a/b/fjRFPVgEf59H5AhA813Z8VH1AAAAAesYzNMYqSKo+pcIYfkI+vom88oWEjiUlGqg5ZnMjCDyAAAAAfhRkr88MfAHkMG4+udFvZTUA+6oxw8zgr9Z1RJ1YzqFAAAAAcAAAAAAAAAABRQxlrlNvI31xsJfiSV60wQRlrJS9dwRdpXz3JQkPjBAAAAAQAAAAAUUMZa5TbyN9cbCX4kletMEEZayUvXcEXaV89yUJD4wQAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAQAAAACa8bKMjcJTsZ9Ur02quGs/sgzhKwauO3s78fGDS75dmAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAABgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAU4oyrfec/IacsMU8hTZbaNRSJKEd0AEk+MRbum8JWngAAAAAQAAAAYAAAABTijKt95z8hpywxTyFNlto1FIkoR3QAST4xFu6bwlaeAAAAADAAAAAQAAAAEAAAAGAAAAAU4oyrfec/IacsMU8hTZbaNRSJKEd0AEk+MRbum8JWngAAAAAwAAAAIAAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAU4oyrfec/IacsMU8hTZbaNRSJKEd0AEk+MRbum8JWngAAAAAQGZnocAAOQcAAAEhAAAAAAABrtPAAAAAA==```

invalid XDR after completing the third point: 
```AAAAAgAAAAAUUMZa5TbyN9cbCX4kletMEEZayUvXcEXaV89yUJD4wQAGu7MBa2KiAABDsgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAABl5iPhP6n9Isibt/1Nfhty4VAS/cIJd/2f0za4fhJqaQAAAAEc3dhcAAAAAQAAAASAAAAAAAAAAAUUMZa5TbyN9cbCX4kletMEEZayUvXcEXaV89yUJD4wQAAABAAAAABAAAAAQAAABEAAAABAAAAAwAAAA8AAAAJYXNrX2Fzc2V0AAAAAAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAAA8AAAAUYXNrX2Fzc2V0X21pbl9hbW91bnQAAAAAAAAADwAAAAtvZmZlcl9hc3NldAAAAAASAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAABgAAAAAAAABkAAAACgAAAAAAAAAAAAAAAAAehIAAAAABAAAAAAAAAAAAAAABl5iPhP6n9Isibt/1Nfhty4VAS/cIJd/2f0za4fhJqaQAAAAEc3dhcAAAAAQAAAASAAAAAAAAAAAUUMZa5TbyN9cbCX4kletMEEZayUvXcEXaV89yUJD4wQAAABAAAAABAAAAAQAAABEAAAABAAAAAwAAAA8AAAAJYXNrX2Fzc2V0AAAAAAAAEgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAAA8AAAAUYXNrX2Fzc2V0X21pbl9hbW91bnQAAAAAAAAADwAAAAtvZmZlcl9hc3NldAAAAAASAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAABgAAAAAAAABkAAAACgAAAAAAAAAAAAAAAAAehIAAAAABAAAAAAAAAAFOKMq33nPyGnLDFPIU2W2jUUiShHdABJPjEW7pvCVp4AAAAARzd2FwAAAABQAAABIAAAAAAAAAABRQxlrlNvI31xsJfiSV60wQRlrJS9dwRdpXz3JQkPjBAAAAEgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAAAoAAAAAAAAAAAAAAAAAHoSAAAAAAAAAAAYAAAAAAAAAZAAAAAEAAAAAAAAAASW0/NhZrsL6Y0hDjEibPDwQyYttIb5P08swy2iVPvl3AAAACHRyYW5zZmVyAAAAAwAAABIAAAAAAAAAABRQxlrlNvI31xsJfiSV60wQRlrJS9dwRdpXz3JQkPjBAAAAEgAAAAFOKMq33nPyGnLDFPIU2W2jUUiShHdABJPjEW7pvCVp4AAAAAoAAAAAAAAAAAAAAAAAHoSAAAAAAAAAAAEAAAAAAAAACgAAAAYAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk/TyzDLaJU++XcAAAAUAAAAAQAAAAYAAAABTijKt95z8hpywxTyFNlto1FIkoR3QAST4xFu6bwlaeAAAAAPAAAABkNPTkZJRwAAAAAAAQAAAAYAAAABTijKt95z8hpywxTyFNlto1FIkoR3QAST4xFu6bwlaeAAAAAUAAAAAQAAAAYAAAABeSqCyQenKLXJz+2gWLbnh9rHmWFyoaFXIhuRZIbIk5EAAAARAAAAAQAAAAIAAAAPAAAAB3Rva2VuX2EAAAAAEgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAAA8AAAAHdG9rZW5fYgAAAAASAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SWAAAAAQAAAAYAAAABeSqCyQenKLXJz+2gWLbnh9rHmWFyoaFXIhuRZIbIk5EAAAAUAAAAAQAAAAYAAAABl5iPhP6n9Isibt/1Nfhty4VAS/cIJd/2f0za4fhJqaQAAAAUAAAAAQAAAAYAAAABre/OWa7lKWj3YGHUlMJSW3Vln6QpamX0me8p5WR35JYAAAAUAAAAAQAAAAdgMyuhKAHtplh06a/b/fjRFPVgEf59H5AhA813Z8VH1AAAAAesYzNMYqSKo+pcIYfkI+vom88oWEjiUlGqg5ZnMjCDyAAAAAfhRkr88MfAHkMG4+udFvZTUA+6oxw8zgr9Z1RJ1YzqFAAAAAcAAAAAAAAAABRQxlrlNvI31xsJfiSV60wQRlrJS9dwRdpXz3JQkPjBAAAAAQAAAAAUUMZa5TbyN9cbCX4kletMEEZayUvXcEXaV89yUJD4wQAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAAAQAAAACa8bKMjcJTsZ9Ur02quGs/sgzhKwauO3s78fGDS75dmAAAAAFVU0RDAAAAADuZETgO/piLoKiQDrHP5E82b32+lGvtB3JA9/Yk3xXFAAAABgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAU4oyrfec/IacsMU8hTZbaNRSJKEd0AEk+MRbum8JWngAAAAAQAAAAYAAAABTijKt95z8hpywxTyFNlto1FIkoR3QAST4xFu6bwlaeAAAAADAAAAAQAAAAEAAAAGAAAAAU4oyrfec/IacsMU8hTZbaNRSJKEd0AEk+MRbum8JWngAAAAAwAAAAIAAAABAAAABgAAAAGt785ZruUpaPdgYdSUwlJbdWWfpClqZfSZ7ynlZHfklgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAU4oyrfec/IacsMU8hTZbaNRSJKEd0AEk+MRbum8JWngAAAAAQGZnocAAOQcAAAEhAAAAAAABrtPAAAAAVCQ+MEAAABAVWGXIYjgYdJBgOhBE6vtUHdND3dJLL41gXhi8ZityMr+Urae6P9MfuMUqkcrpoX2LT4r/SvRPClsLLrhpVcIDg==```

Thanks.

**Comment by christian-rogobete** [comment]
Hello @let-it-snow, thank you for adding this issue. I fixed it in [release 2.6.2](https://github.com/Soneso/stellar-ios-mac-sdk/releases/tag/2.6.2)
