### ISSUE TITLE
IOS 9 crashing while creating SHA512 hash

### ISSUE THREAD

**Issue by GoodX-Network** [Soneso/stellar-ios-mac-sdk#17]
Crash in one of third party libs
// ||||||||||||||||                       SMP Core.swift                       ||||||||||||||||
// Created by Marcel Kröker on 30.09.16.
// Copyright (c) 2016 Blubyte. All rights reserved.

For Big Int, while trying to make 2048 iterations SHA512 hash from 24 words.

**Comment by chelemen-razvan** [comment]
Do you have some sample code to reproduce?

**Comment by GoodX-Network** [comment]
We will try to reproduce in emulator. Cause we got this error on iPod device which runs IOS9

**Comment by chelemen-razvan** [comment]
Ok, if you could share the snippet that causes the crash it would help.
