### ISSUE TITLE
Using the iOS SDK on an application extension

### ISSUE THREAD

**Issue by umdemir** [Soneso/stellar-ios-mac-sdk#19]
I am trying to use the iOS SDK in a network extension and getting these ld warnings:

ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/umit/Library/Developer/Xcode/DerivedData/Meshkat-gwogyokwgikwifetcprpfclgujwh/Build/Products/Release-iphoneos/stellarsdk.framework/stellarsdk

According to documentation, submitting my app to iTunes Connect without clearing these warnings will cause a rejection.

https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html

Again from documentation:

"To configure an app extension target to use an embedded framework, set the target’s “Require Only App-Extension-Safe API” build setting to Yes. If you don’t, Xcode reminds you to do so by displaying the warning “linking against dylib not safe for use in application extensions”."

Thanks a lot!

**Comment by chelemen-razvan** [comment]
Unfortunately there is no easy way to solve your issue using cocoapods. You can fix it by setting the “Require Only App-Extension-Safe API” build setting to Yes in the stellar sdk, building it and manually including it in your project. If you really want it included using cocapods you could also change that setting in the Pod project and it would persist until the next `pod  install`, but this is quite error prone. The future plans for the library do not seem to break the extension safeness but we would rather keep the flag disabled for now and if necessary we will find a solution for extensions also.

**Comment by umdemir** [comment]
Thank you for your quick response!

I am using submodules and waiting for Carthage support actually. I've already set that flag but.. Is there a way to fix this and still get latest updates from this repository? I want to keep the SDK up to date.

Thanks!

**Comment by umdemir** [comment]
Another solution could be creating configurations like Debug (Application Extension), Release (Application Extension) and set that flag only for those configurations. I can make the changes and create a pull request for you. So you guys can consider it maybe?

**Comment by chelemen-razvan** [comment]
I don't think its a good idea to impose a restriction on configurations naming. Also having to maintain two separate pods (and a separate podspec repository) only for this issue seems like overkill...so you see the dilemma. What I'm looking for is a smart workaround but I wasn't able to come by any yet. Regarding Carthage support we'll probably add that soon if its requested.

**Comment by umdemir** [comment]
Thank you for the explanation. I will create a separate issue for the Carthage support.
