### ISSUE TITLE
Carthage Update Error

### ISSUE THREAD

**Issue by umdemir** [Soneso/stellar-ios-mac-sdk#23]
"carthage update" command gives this error:

"*** Skipped building stellar-ios-mac-sdk due to the error:
Dependency "stellar-ios-mac-sdk" has no shared framework schemes"

To reproduce, add "github "soneso/stellar-ios-mac-sdk" ~> 1.1.4" to Cartfile and then run "carthage update"

**Comment by chelemen-razvan** [comment]
Looks like we had to do a new release for Carthage to work, just switch to 1.1.5 and you should be good now.

**Comment by umdemir** [comment]
After "carthage update", I shared the schemes (so there's a framework scheme but not shared) and build it with "carthage build" then it was built. I had to do these steps anyway to change another build flag.
