### ISSUE TITLE
Decode and sign transactions

### ISSUE THREAD

**Issue by keroglu** [Soneso/stellar-ios-mac-sdk#34]
I would like to decode an unsigned transaction envelope that is created and encoded (Base64 XDR) on my backend (Java). Then I want to sign it, and send it back to the server encoded.
Is it possible using this library?
Thanks,

**Comment by chelemen-razvan** [comment]
Sure you can decode the transaction enveloper using `let envelope = try! TransactionEnvelopeXDR(xdr: <your_xdr_string_from_backend>)`. Then you can sign the transaction and add your signature to the envelope and convert it back to xdr. Something like this:
```
let tx = envelope.tx
// user signature
let transactionHash = try [UInt8](tx.hash(network:.testnet))
// userKeyPair - the keypair to sign the transaction with
let userSignature = userKeyPair.signDecorated(transactionHash)
envelope.signatures.append(userSignature)
let xdrEncodedEnvelope = envelope.xdrEncoded
// send it back to your server
```
