### ISSUE TITLE
EventSource missing return in didCompleteWithError?

### ISSUE THREAD

**Issue by ndizazzo** [Soneso/stellar-ios-mac-sdk#39]
@chelemen-razvan  (tagging since you worked on this originally)

I noticed quite a bit of error output being logged when using any streaming endpoint for an account. 

Digging in, I saw that [Apple's documentation states](https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/1411610-urlsession) that `urlSession(... didCompleteWithError)` is only called when error on the client side is encountered, but not when a server side error is encountered. 

To test this out, I added an implementation of `urlSession(... didBecomeInvalidWithError)` delegate method to see if there actually is a server side error, but this delegate method is not called. 

So if there aren't really any errors, wouldn't the SDK need a `return` in the block where the nil check for error is (right after line 184)?

https://github.com/Soneso/stellar-ios-mac-sdk/blob/020563f6d098618c1153e507ba9020b730961691/stellarsdk/stellarsdk/utils/EventSource.swift#L179

As implemented right now when there's no error, `self.connect()` will be called in this block, and then the error callback will immediately be invoked if there is one. 

It seems to me like this should return in that block after re-establishing the stream connection instead of continuing on, but I'm not really sure about the intentions of the implementation.

**Comment by chelemen-razvan** [comment]
Although I put the streaming part together that code is from some other project. I think you are right, what you're saying makes sense logically and I had some trouble with streaming responses also. Did you test this?

**Comment by ndizazzo** [comment]
Yeah I’ve been playing around with it locally and it seems to be normal
with that change... I’ll whip up a quick PR with a fix.

-- 
Nick DiZazzo

**Comment by chelemen-razvan** [comment]
You can make a pr and we'll merge it.
