### ISSUE TITLE
Unable to Build and Submit Accounts

### ISSUE THREAD

**Issue by thisiseshan** [Soneso/stellar-ios-mac-sdk#44]
Account ID: GAWE7LGEFNRN3QZL5ILVLYKKKGGVYCXXDCIBUJ3RVOC2ZWW6WLGK76TJ
Account Sequence: 513197052264508
Account balance: 9954.4994000 XLM
Sample: Horizon request error of type request failed with message: {
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This is usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}
Sample: Horizon Error response type: https://stellar.org/horizon-errors/not_found
Sample: Horizon Error response tite: Resource Missing
Sample: Horizon Error response httpStatusCode: 404
Sample: Horizon Error response detail: The resource at the url requested was not found.  This is usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided.
Sample: Horizon Error response instance: unspecified

**Comment by thisiseshan** [comment]
**This is my code. It is not in the viewDidLoad Method**




do {
        let sourceAccountKeyPair = try KeyPair(secretSeed:"SA3QF6XW433CBDLUEY5ZAMHYJLJNHBBOPASLJLO4QKH75HRRXZ3UM2YJ")
        let destinationAccountKeyPair = try KeyPair(accountId: "GCKECJ5DYFZUX6DMTNJFHO2M4QKTUO5OS5JZ4EIIS7C3VTLIGXNGRTRC")
            
            
            
            sdk.accounts.getAccountDetails(accountId: sourceAccountKeyPair.accountId) { (response) -> (Void) in
                switch response {
                case .success(let accountResponse): // account exists
                    do {
                        // create the payment operation
                        let paymentOperation = PaymentOperation(sourceAccount: sourceAccountKeyPair,
                                                                destination: destinationAccountKeyPair,
                                                                asset: Asset(type: AssetType.ASSET_TYPE_NATIVE)!,
                                                                amount: 10.0)
                        
                        // create the transaction containing the payment operation
                        let transaction = try Transaction(sourceAccount: accountResponse,
                                                          operations: [paymentOperation],
                                                          memo: Memo.none,
                                                          timeBounds:nil)
                        
                        // Sign the transaction to prove you are actually the person sending it.
                        try transaction.sign(keyPair: sourceAccountKeyPair, network: Network.testnet)
                        
                        // And finally, send it off to Stellar!
                        try sdk.transactions.submitTransaction(transaction: transaction) { (response) -> (Void) in
                            switch response {
                            case .success(_):
                                print("Transaction successfully sent!")
                            case .failure(let error):
                                StellarSDKLog.printHorizonRequestErrorMessage(tag:"Sample", horizonRequestError:error)
                            }
                        }
                    } catch {
                        print ("...")
                    }
                case .failure(let error):
                    StellarSDKLog.printHorizonRequestErrorMessage(tag:"Sample", horizonRequestError:error)
                    
                }
            }
        } catch {
            print("...")
        }

**Comment by krrisztian** [comment]
How did you resolve this issue? I'm facing it too.

**Comment by thisiseshan** [comment]
Hey @krrisztian 

It takes sometime for the testnet to generate accounts from key pairs. This error is displayed if data is requested from non-existing accounts. Here's a little trick I used to solve the problem.
Once you have your TestAccount created. Use the code below to give a delay of 15 seconds just before fetching details from the account, this will give enough time for the accounts to be built before any data is fetched from them.

In order:
1) Generate Key Pairs
2) Build Accounts
3) Give Delay of ~15 seconds
4) Include getAccountDetails() in the parenthesis of the below code to access data

`DispatchQueue.main.asyncAfter(deadline: .now() + 15.0) {
sdk.accounts.getAccountDetails()
}`

Cheers!
