### ISSUE TITLE
Data Couldn't Be Read Because it is Missing

### ISSUE THREAD

**Issue by p3scobar** [Soneso/stellar-ios-mac-sdk#48]
I'm trying to fetch the details of an account, but I'm receiving the following error:

`failure(error: stellarsdk.HorizonRequestError.parsingResponseFailed(message: "The data couldn’t be read because it is missing."))`

My best guess is that I'm somehow making the request on the wrong network, but I really don't have a clue. Here is my code:

`Stellar.sdk.accounts.getAccountDetails(accountId: accountId) { (response) -> (Void) in`

The Stellar struct looks like this:

```
public struct Stellar {
    static let sdk = StellarSDK(withHorizonUrl: HorizonServer.url)
    static let network = Network.testnet
}

public struct HorizonServer {
    static let production = "https://horizon.stellar.org"
    static let test = "https://horizon-testnet.stellar.org/"
    static let url = HorizonServer.test
}

**Comment by ndizazzo** [comment]
hey @p3scobar, that's the error that gets returned by the SDK when the Horizon API returns a 404 when querying for account data, which in my experiences during development, means the account doesn't exist on the network. 

Testnet was wiped at the end of February - if you were using an account that you were expecting to still exist and was created before that reset, that might be your issue?

If that's not the problem, post the `accountId` that you're using so we can have all the details and see what's up.

**Comment by p3scobar** [comment]
Thanks for the reply. That doesn't seem to be the issue, because I can view this account on the testnet:

GCDSDSK6AX2M5JJBP44ULV5FNX7MMOPAHSZEDEJWAQJX3OGTKGW7IC27

**Comment by christain-rogobete** [comment]
remove the "/" at the end of your test horizon url and try again pls.

**Comment by p3scobar** [comment]
Still the same error.

**Comment by ndizazzo** [comment]
I dug in here a bit. The / shouldn't have any effect. Checking out the network request and response, testnet actually does respond with the JSON for the account:

<img width="1792" alt="Screen Shot 2019-03-13 at 10 04 29 AM" src="https://user-images.githubusercontent.com/728690/54285042-89647e00-4577-11e9-81bc-e66a004c818c.png">

The `AccountResponse` object is failing to parse on line 87 for `signers`: `signers = try values.decode(Array.self, forKey: .signers)`

This corresponds to some changes that happened in [Horizon 17](https://github.com/stellar/go/blob/master/services/horizon/CHANGELOG.md), which were addressed in [this PR](https://github.com/Soneso/stellar-ios-mac-sdk/pull/45).

@p3scobar If you target your pod file to pull from `master`, you should be able to get around this error until the next version of the SDK is deployed on cocoapods that includes this PR:

`pod 'stellar-ios-mac-sdk', :git => 'https://github.com/Soneso/stellar-ios-mac-sdk.git'`

Here are my results with your account ID after updating:

<img width="917" alt="Screen Shot 2019-03-13 at 10 14 29 AM" src="https://user-images.githubusercontent.com/728690/54285694-d6951f80-4578-11e9-94d1-eced567af20c.png">

**Comment by ndizazzo** [comment]
Actually - looks like it was deployed in 1.6.0. by @christain-rogobete. You should just be able to update your pod installation and carry on 👍

**Comment by christain-rogobete** [comment]
yes, it works for me too

**Comment by p3scobar** [comment]
Ok, it works on my end as well. I swear I had 1.6.0 installed, but after deintegrating my pod file & reinstalling, it works. Thank you very much for your help gents.
