### ISSUE TITLE
getAccountDetails not working !

### ISSUE THREAD

**Issue by PavelSakhanko** [Soneso/stellar-ios-mac-sdk#52]
Hi, I need Your help !

I'm created account in test net and checking it - he exists.
When I using getAccountDetails with "https://horizon-testnet.stellar.org" - I have error "The data couldn’t be read because it is missing."
When "https://horizon.stellar.org" as in the example above -

notFound(message: "{\n "type": "https://stellar.org/horizon-errors/not_found\",\n "title": "Resource Missing",\n "status": 404,\n "detail": "The resource at the url requested was not found. This is usually occurs for one of two reasons: The url requested is not valid, or no data in our database could be found with the parameters provided."\n}", horizonErrorResponse: Optional(<stellarsdk.NotFoundErrorResponse: 0x281e3fe30>))

my account "GB33EPYLVRLD6GTCRLSBCXET35TZKJJCQDRQZHLR5UNNNWWTHMD4IL4B".

And I using

let sdk = StellarSDK.init(withHorizonUrl: "https://horizon.stellar.org")
let account = "GB33EPYLVRLD6GTCRLSBCXET35TZKJJCQDRQZHLR5UNNNWWTHMD4IL4B"

sdk.accounts.getAccountDetails(accountId: account) { response -> Void in
switch response {
case .success(let details):
print(details.balances)
print(details.accountId)
case .failure(let error):
print(error)
}
}

But it's not works for me.
Thank You !

**Comment by christain-rogobete** [comment]
Hi Pavel,

pls. check if you are using the current version of the SDK.
See also:
https://github.com/Soneso/stellar-ios-mac-sdk/issues/48

Hope this helps
Chris.

**Comment by PavelSakhanko** [comment]
Thank You! 

In my case updating of pod helped me!
in pod file I change  pod 'stellar-ios-mac-sdk', '~> 1.5.6'.    to pod 'stellar-ios-mac-sdk', :git => 'https://github.com/Soneso/stellar-ios-mac-sdk.git' 

Thank You! 
Best regards!
