### ISSUE TITLE
Archiving an iOS app using Xcode 10.2 and latest version of this SDK takes hours

### ISSUE THREAD

**Issue by cstephens-phunware** [Soneso/stellar-ios-mac-sdk#53]
After updating to Xcode 10.2, with or without Swift 5 updates and consuming the stellar-ios-mac-sdk 1.6.0 cocoapod our iOS app archive times have gone from less than 2 minutes to upwards of 5 hours.

**Comment by cstephens-phunware** [comment]
FWIW, it looks related to this Swift 5 bug:
https://bugs.swift.org/browse/SR-10209

After I removed a significant portion of the words in each array in WordList.swift, the archiving time dropped significantly. It looks like they fixed the Swift issue but I'm not sure when it will make it into an Xcode build. Might be worthwhile to pull in the words from a resource file to avoid this issue?

**Comment by christain-rogobete** [comment]
Hi cstephens-phunware,

thank you for providing this solution. It is now available in v. 1.6.3.

Best Chris.
