### ISSUE TITLE
Unify client / app headers across SDKs

### ISSUE THREAD

**Issue by tomquisel** [Soneso/stellar-ios-mac-sdk#54]
Just a note that @nikhilsaraf just [added](https://github.com/stellar/go/pull/1072/files) headers that look similar to the `X-Client-Application` header just added to this SDK. It'd be great to replace `X-Client-Application` with `X-App-Name` and `X-App-Version` to stay unified.

**Comment by christain-rogobete** [comment]
Hello Tom, thank you for your note. I replaced it. Its is now available in version 1.6.3
