### ISSUE TITLE
Added stellar-ios-mac-sdk in my framework.

### ISSUE THREAD

**Issue by maxvlasenko91** [Soneso/stellar-ios-mac-sdk#55]
Hi, I have a problem. I make my library based on yours but there are problems in the absence of modules.

My flow: 
1- Create Cocoa touch framework
2- Pod init
3- past this in pod file :

          _platform :ios, '9.0'
          target 'ProstoLibrary' do
          use_modular_headers!
           pod 'stellar-ios-mac-sdk', '~> 1.5.6'
end_

4- pod install
5- open *.xcworkspace
6- cmd+b
7- error (no such module)
<img width="267" alt="Screen Shot 2019-04-17 at 2 55 32 PM" src="https://user-images.githubusercontent.com/49400082/56286371-3788b800-6122-11e9-8e3b-d3c9b83c6038.png">

Who faced, tell me how to solve this problem please. Or maybe some other flow.

**Comment by maxvlasenko91** [comment]
Developers, please tell me if your sdk is optimized for integration into third-party libraries? 
I can't validate when I write pod spec lint, i always get the same error:
- ERROR | [iOS] xcodebuild: no such module 'stellarsdk'.
Please, tell me how to solve this problem.

**Comment by krrisztian** [comment]
Without more info my best guess would be to try and build the project before trying to import the library.
How did you added it in the first place (pod, Carthage, manually)?

**Comment by maxvlasenko91** [comment]
@krrisztian Hi, thx for response, I will try to describe all the options that I have tried.
-Create Cocoa Touch Framework.
When i install Carthage (github "soneso/stellar-ios-mac-sdk" ~> 1.1.5), it's ok.
Next i use 'pod lib lint' - its ok, passed validation.
But when import stellarsdk in swift file, and next i use 'pod lib lint' i have error  - ERROR | xcodebuild:  **/Alogaraj.swift:10:8: error: no such module 'stellarsdk'.

If you can, please write a step-by-step flow how to import your sdk correctly into my framework. Maybe I'm missing something, or I'm doing it wrong.

**Comment by chelemen-razvan** [comment]
I'm not sure what you're trying to achieve here. Having nested frameworks it is not as easy as you describe above, you can search for `Umbrella framework` to find out more. Our framework has nothing special in this regard so if you can nest a dummy framework in your umbrella framework you could just replace it with the stellarsdk.

**Comment by maxvlasenko91** [comment]
@chelemen-razvan I have already solved the problem with integrating your SDK into my framework. The problem was that the C module of files does not just see xcode, and i write in *. modulemap "header "ed25519.h "" ,everything worked out. Thx.
