### ISSUE TITLE
swift payments.stream                 HELP WANTED

### ISSUE THREAD

**Issue by PavelSakhanko** [Soneso/stellar-ios-mac-sdk#56]
Hello!
I'm using code for detect any payments to the my wallet:

StellarSDK().payments.stream(for: .paymentsForAccount(account: Account.accountID, cursor: "now")).onReceive { (response) -> (Void) in
            switch response {
            case .open:
                break
            case .response(let id, let operationResponse):
                if let paymentResponse = operationResponse as? PaymentOperationResponse {
                    switch paymentResponse.assetType {
                    case AssetTypeAsString.CREDIT_ALPHANUM4:
                        print("Payment of \(paymentResponse.amount) from \(paymentResponse.sourceAccount) received -  id \(id)" )
                    default:
                        print("Payment of \(paymentResponse.amount) \(paymentResponse.assetCode!) from \(paymentResponse.sourceAccount) received -  id \(id)" )
                    }
                }
            case .error(let err):
                print(err?.localizedDescription ?? "Error")
            }
        }

Account.accountID - it's my wallet account id.
I got money transaction (+ on my wallet), but I have't see any result via this stream!
Can you help me? What I'm doing wrong?

**Comment by christain-rogobete** [comment]
Hi Pavel,

thank you for adding this issue. Seams that the stream item gets released faster now with swift 5. Can you please try to hold a reference to it somewhere? E.g.

class PaymentsTestCase: XCTestCase {
var streamItem:OperationsStreamItem? = nil

....

streamItem = sdk.payments.stream(for: .paymentsForAccount(account: destinationAccountKeyPair.accountId, cursor: "now"))

streamItem?.onReceive { (response) -> (Void) in
                switch response {
                case .open:
...

you can also use the reference later to close the streaming if you don't need it any more.

see also "PaymentsTestCase.swift" in the latest commit of the sdk,. Test case: "testSendAndReceiveNativePayment" Line: 125.

**Comment by PavelSakhanko** [comment]
Hi, thank's a lot !!!

**Comment by bas24** [comment]
Hi guys, thank you for library!

Could you, please provide with some example how to make working payment stream when application is in background? Thank you in advance!

When app is in foreground all work like expected, when in background nothing and after entering foreground the following error:
HTTP load failed (error code: 53 [1:53])
finished with error - code: 53
load failed with error Error
load failed with error Error Domain=NSPOSIXErrorDomain Code=53 "Software caused connection abort" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <694DD23A-7B6A-417C-A281-C693AF311BF3>.<1>, _kCFStreamErrorDomainKey=1, NSErrorPeerAddressKey=<CFData 0x2814b3110 [0x24010d430]>{length = 16, capacity = 16, bytes = 0x100201bb22edc33f0000000000000000}, _kCFStreamErrorCodeKey=53, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <694DD23A-7B6A-417C-A281-C693AF311BF3>.<1>" 

than value is printed to console output.
