### ISSUE TITLE
Stellar Protocol 11 Compatibility

### ISSUE THREAD

**Issue by theaeolianmachine** [Soneso/stellar-ios-mac-sdk#57]
Protocol V11 of Stellar adds a new `manage_buy_offer` operation. Also names of `manage_offer` and `create_passive_offer` have been changed to `manage_sell_offer` and `create_passive_sell_offer`.

References:
* https://github.com/stellar/go/pull/1164
* https://github.com/stellar/stellar-protocol/blob/master/core/cap-0006.md
* [XDR files diff](https://github.com/stellar/stellar-core/compare/v10.3.0...v11.0.0#diff-01cb6b2520b4d5097b53837c1c18c5a3) - this shows all changes between v10.3.0 and v11.0.0 in Stellar Core — you'll need to just look at the changes in `src/xdr` (realistically any file that ends with a `.x` extension).

Let me know if you have any questions!

**Comment by christain-rogobete** [comment]
Hello Johnny,
thank you for the hint. I'll take care of the changes.
Best
Christian.

**Comment by theaeolianmachine** [comment]
Is this resolved by #62?

**Comment by christain-rogobete** [comment]
Yes :)
