### ISSUE TITLE
SDK compilation error with Xcode9.3 and Swift4.1

### ISSUE THREAD

**Issue by YaroslavBV** [Soneso/stellar-ios-mac-sdk#6]
SDK compilation error with new Xcode and Swift4.1.

![screen shot 2018-04-02 at 11 09 27](https://user-images.githubusercontent.com/2678674/38188855-62c9346e-3666-11e8-83df-9673c1b5be90.png)

**Comment by VladimirMitin** [comment]
The same situation.

**Comment by chelemen-razvan** [comment]
Looks like there are some half changes in swift 4.1. The library code is affected by https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20171204/006107.html, until that is implemented we will try to find a workaround, but in the meanwhile you should stay to swift 4.0.

**Comment by chelemen-razvan** [comment]
Solved in 1.1.2 release.
