### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by lukereichold** [Soneso/stellar-ios-mac-sdk#60]
As a developer, I would like to be able to use the native Swift Package Manager (SPM) to install and consume the SDK. Documentation for achieving this can be found on the [Swift.org website](https://swift.org/package-manager/).

This is motivated by the desire to use pure Swift projects, such as server-side Swift frameworks like [Vapor](https://github.com/vapor/vapor), without the need to use external tooling like CocoaPods and Carthage. 

More generally, it may be worth asking, should this be thought of as a "stellar-swift" client, or as a client specific to macOS and iOS as the name/description suggests?

**Comment by christain-rogobete** [comment]
Hi Luke,
thank you for your hint. We will add support for swift package manager.
Best
Christian

**Comment by chelemen-razvan** [comment]
We had a try at Swift Package Manager (SPM) but it its rather inflexible with the project structure / having C and swift in the same package so there is no way to add our lib as a package without having to change the project structure. Maybe the SPM will change this in the future but for now we cannot add support for it.

**Comment by fishcharlie** [comment]
Any updates on this? Not sure if [this article](https://rderik.com/blog/making-a-c-library-available-in-swift-using-the-swift-package/) is relevant in this case, but might be helpful. I know SPM has made a lot of improvements recently, but haven't kept up to date on if C support is part of those improvements.
