### ISSUE TITLE
KeyPair secreteseed falsely accepts public key

### ISSUE THREAD

**Issue by krrisztian** [Soneso/stellar-ios-mac-sdk#61]
After fighting with a 404 "Resource Missing" response, I realized that I have mistakenly provided a public key instead of a secret key into the following function:
`let sourceAccountKeyPair = try! KeyPair(secretSeed: "G...")`

I think a good solution to this would be to check the first character that it's in fact a secret key since they all start with an "S" and all public keys start with a "G". -> print or throw an error

**Comment by christain-rogobete** [comment]
Hey krrisztian, 
thank you for the hint. We will improve this.
Best
Chris.

**Comment by christain-rogobete** [comment]
added the check with commit da0a82b
