### ISSUE TITLE
Path Payment Path Assets not optional

### ISSUE THREAD

**Issue by krrisztian** [Soneso/stellar-ios-mac-sdk#65]
Creating a path payment operation seems to require the path of assets a transaction goes through. I would like to have it optional and let the Stellar network decide what path to take.

Is that possible? I tried building a path payment transaction without the path: [Asset] option but it will not let me as it is not optional.

**Comment by christain-rogobete** [comment]
Hi @krrisztian, 

thats not possible since path is required - see: https://www.stellar.org/developers/horizon/reference/resources/path.html

You may try to find a path using the PaymentPathsService. See also:
https://www.stellar.org/developers/horizon/reference/endpoints/path-finding.html
