### ISSUE TITLE
I can't check balance from this day....(ios).

### ISSUE THREAD

**Issue by PavelSakhanko** [Soneso/stellar-ios-mac-sdk#67]
Hi!
I used code such as: 
sdk.accounts.getAccountDetails(accountId: keyPair.accountId) { (response) -> (Void) in
    switch response {        from https://github.com/Soneso/stellar-ios-mac-sdk

in my implementation:

 StellarSDK().accounts.getAccountDetails(accountId: Account.getAccountID()) { (response) -> Void in
            switch response {
            case .success(let accountDetails):

                for balance in accountDetails.balances {

                    switch balance.assetType {
                    case AssetTypeAsString.CREDIT_ALPHANUM4:

                        DispatchQueue.main.async {
                            completion((balance.balance.currencyFormatting(), balance.assetCode!, balance.balance))
                        }
                    default: break
                    }
                }
            case .failure(let error):
                print(error.localizedDescription)
            }
        }

accountId - correct
I see response error The operation couldn’t be completed. (stellarsdk.HorizonRequestError error 11.). 
Yesterday everything worked correctly and I did not make any changes to the code. 

I need Your help!

**Comment by christain-rogobete** [comment]
Hi @PavelSakhanko, did you already update to the latest version 1.6.6?
See: https://github.com/Soneso/stellar-ios-mac-sdk/issues/66

**Comment by PavelSakhanko** [comment]
> Hi @PavelSakhanko, did you already update to the latest version 1.6.6?
> See: #66

great thanks! all work fine!
