### ISSUE TITLE
Question about streaming

### ISSUE THREAD

**Issue by Ebioro** [Soneso/stellar-ios-mac-sdk#68]
Hi Guys,

I am giving it a try to your sdk and have a question related to streaming. Will the sdk try to reconnect in case the connection is dropped due to errors? In [here](https://www.stellar.org/developers/horizon/reference/tutorials/follow-received-payments.html) the guys from stellar recommend to use their sdk because for some errors the event source object will not reconnect. 

Thanks in advance!

**Comment by chelemen-razvan** [comment]
Hello,

I've never tried this, but this should work exactly as the EventSource javascript library, so my guess would be that it would not reconnect in those cases, however you can give it a try. If you get a specific case we can investigate this further.
