### ISSUE TITLE
Payment stream in in background

### ISSUE THREAD

**Issue by bas24** [Soneso/stellar-ios-mac-sdk#72]
Hi guys, thank you for library!

Could you, please provide with some example how to make working payment stream when application is in background? Thank you in advance!

I've edited my code as explained here: https://github.com/Soneso/stellar-ios-mac-sdk/issues/56#issuecomment-487841620

When app is in foreground all work like expected, when in background nothing and after entering foreground the following error:
HTTP load failed (error code: 53 [1:53])
finished with error - code: 53
load failed with error Error
load failed with error Error Domain=NSPOSIXErrorDomain Code=53 "Software caused connection abort" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <694DD23A-7B6A-417C-A281-C693AF311BF3>.<1>, _kCFStreamErrorDomainKey=1, NSErrorPeerAddressKey=<CFData 0x2814b3110 [0x24010d430]>{length = 16, capacity = 16, bytes = 0x100201bb22edc33f0000000000000000}, _kCFStreamErrorCodeKey=53, _NSURLErrorRelatedURLSessionTaskErrorKey=(
"LocalDataTask <694DD23A-7B6A-417C-A281-C693AF311BF3>.<1>"

than value is printed to console output.

**Comment by christain-rogobete** [comment]
Hello @bas24,

as far as I know, it is not possible to keep the streaming while the app is in background. It will be closed by iOS. What you need to make that work is a server side solution that sends push notifications to your app in case something changed in the users account (e.g. payment received).

Hope this helps.

**Comment by ndizazzo** [comment]
It's possible for you to use [background fetch](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/updating_your_app_with_background_app_refresh) if iOS wakes up your application. it's a less heavy-handed approach than push notifications with a data payload.

**Comment by bas24** [comment]
Thank you guys for replies, already done handling everything on server.
