### ISSUE TITLE
Add transaction fee to a Transaction object from parsed XDR string

### ISSUE THREAD

**Issue by Ebioro** [Soneso/stellar-ios-mac-sdk#76]
Hi guys, at this moment you are only adding  maxOperationFee to transactions created with your sdk. However, maxOperationFee is not included when parsing a XDR string. To be more specific, the following is the scenario I think the sdk should cover:

1. There is a tx with a fee, of let us say of 1000 stroops, that is sent to the ios client to be signed
2. the client parses XDR string and takes the fee in addition to the other fields needed
3. The client creates a tx and signs it

Currently, if you send a tx to be signed by the sdk, the sdk overwrites whatever fee was sent with the default 100 stroops. I see that this is because you are taking the fee coming in the XDR in your convenience init methods in lines 71 and 95

**Comment by christain-rogobete** [comment]
Hi @Ebioro,

thank you for reporting this issue. I fixed it with this commit:
https://github.com/Soneso/stellar-ios-mac-sdk/commit/8efe9ea5bb69d3b2c2c27a54418c47f2f8ca426f

Kind regards
Christian

**Comment by Ebioro** [comment]
Ah great man! Are you planning to create a new release for this?

**Comment by christain-rogobete** [comment]
Done

**Comment by Ebioro** [comment]
thanks a lot!

**Comment by tabathap** [comment]
👌

**Comment by Ebioro** [comment]
btw. I am using Cocoapods to get the latest release. But get an error when trying to install it. Is it already available there?

**Comment by christain-rogobete** [comment]
Yes, its there since yesterday
<img width="599" alt="Screenshot 2019-10-10 at 12 53 09" src="https://user-images.githubusercontent.com/35729606/66563037-32e70e80-eb5d-11e9-8bd8-efa291d9b132.png">

what kind of error do you get?

**Comment by Ebioro** [comment]
ah thanks. Fixed it with pod install --repo-update. And thanks again for the great work you are doing with this SDK

**Comment by christain-rogobete** [comment]
yw. I will close this issue now
