### ISSUE TITLE
submitTransaction error

### ISSUE THREAD

**Issue by PavelSakhanko** [Soneso/stellar-ios-mac-sdk#78]
Hi! There is a problem. 
I created a new account on the public network and I can verify this using https://stellar.expert/explorer/public/.
Everything is correct - the account is open. To get account details, I use StellarSDK (withHorizonUrl: "https://horizon.stellar.org") .accounts.getAccountDetails - and get a valid response. 
Next, I need to change the trustline for which I call try StellarSDK (withHorizonUrl: "myHorizonUrl") .transactions.submitTransaction (transaction: transaction).
 In this call, I use a unique horizonUrl. 
I get error 401 // Unauthorized. What am I doing wrong?
This is an account https://stellar.expert/explorer/public/search?term=GADKWDVTMPW6A6VG7I2SXWYPDJC6SSUNOZKH7JB4C46KVZJZFP75YTIZ
Thanks!

**Comment by christain-rogobete** [comment]
Hi Pavel, it is hard to say ... seams that you are unauthorised... did you try to get the account details  by using your unique horizon url? Is that working?

**Comment by PavelSakhanko** [comment]
> Hi Pavel, it is hard to say ... seams that you are unauthorised... did you try to get the account details by using your unique horizon url? Is that working?

Hi, Christain, thanks for the help! I dealt with this problem.
Best regards!
