### ISSUE TITLE
Update challenge transaction helpers for SEP-10 v1.3.0

### ISSUE THREAD

**Issue by leighmcculloch** [Soneso/stellar-ios-mac-sdk#79]
### Summary

A change has been released in SEP-10 Web Authentication v1.3.0 that adds support for:
 1. Accounts not using the master key as a signer.
 2. Accounts multiple signers.

SEP-10 v1.3.0 Change: stellar/stellar-protocol@ea0d7edc3bed84a24970c5fe5fc34993e6c97e48

The new functionality requires changes to any SDK implementing challenge verification.

### Details and Reference Implementations

The Stellar Go SDK is the first SDK we've implemented this new functionality and it can be used as a reference. It has implemented the following changes and similar changes may be required in this SDK:
 * Deprecated the existing verification function (`VerifyChallengeTx`).
 * Added new functions to:
   * Read the client account ID out of a challenge transaction without verifying client signatures, so that servers can lookup the signers of the account before verifying. (`ReadChallengeTx`)
   * Verify signatures on a challenge transaction meet a threshold. (`VerifyChallengeTxThreshold`)
   * Verify signatures on a challenge transaction match signers. (`VerifyChallengeTxSigners`)
 * Increased the timeout on the challenge transaction from 5 minutes to 15 minutes.

Go SDK Change: stellar/go@8ff0848c31a940ab76f1a9177af0d9dd405ffa9b

An example of a SEP-10 server using the v1.3.0 verification process is implemented here:
https://github.com/stellar/go/tree/master/exp/services/webauth

If anyone has any questions feel free to join us in `#dev-discussion` in `stellar.public` Keybase.

**Comment by christain-rogobete** [comment]
Hi Leigh, thank you for adding this issue. We will take care of it.

**Comment by christain-rogobete** [comment]
Hi Light, 

the iOS SDK implements the client side. In the current version of the SDK there is from my point of view nothing to be added to fulfil the support for:

- Accounts not using the master key as a signer.
- Accounts multiple signers.

Both things are already possible. Therefore I am going to close this issue.

**Comment by leighmcculloch** [comment]
Hi Christian,

That sounds great!

One thing I want to check is that looking at the `jwtToken` function there might be one thing missing from it to support multiple signers. The function assumes the signing key is the account master key.

https://github.com/Soneso/stellar-ios-mac-sdk/blob/master/stellarsdk/stellarsdk/web_authentication/WebAuthenticator.swift#L137-L146

Are you thinking the way for someone doing multi sig web auth is to use the other functions `getChallenge`, `isValidChallenge`, `signTransaction` directly instead of the `jwtToken` function which would remain only used for single key? Makes sense to me because many multi sig setups won't have all the keys in the one app.

Thank you for taking a look at the issue!

**Comment by christain-rogobete** [comment]
Hi Leigh,

thank you for pointing that out. I published a new version 1.7.2 where the mentioned functions are now public, so that they can be used to support multiple signers (as you described above).

Thank you and best regards
Christian.
