### ISSUE TITLE
Failed to parse horizon response, if the transaction history contains path payments

### ISSUE THREAD

**Issue by AlexanderOsokin** [Soneso/stellar-ios-mac-sdk#80]

**Comment by AlexanderOsokin** [comment]
getPayments response failed to parse.

`{
  "_links": {
    "self": {
      "href": "https://horizon.stellar.org/accounts/GB36JPXHJIP34EBRTZ6JVJXL3HEQ65S3CGOID2LKJXBYN2DNLVOFL6FX/payments?cursor=&limit=200&order=desc"
    },
    "next": {
      "href": "https://horizon.stellar.org/accounts/GB36JPXHJIP34EBRTZ6JVJXL3HEQ65S3CGOID2LKJXBYN2DNLVOFL6FX/payments?cursor=114233670373568562&limit=200&order=desc"
    },
    "prev": {
      "href": "https://horizon.stellar.org/accounts/GB36JPXHJIP34EBRTZ6JVJXL3HEQ65S3CGOID2LKJXBYN2DNLVOFL6FX/payments?cursor=120453319889080321&limit=200&order=asc"
    }
  },
  "_embedded": {
    "records": [
      {
        "_links": {
          "self": {
            "href": "https://horizon.stellar.org/operations/120453319889080321"
          },
          "transaction": {
            "href": "https://horizon.stellar.org/transactions/9995108578bdbd281d298cf91cd3c88725c605018e5e2b896e4dd394d3459d82"
          },
          "effects": {
            "href": "https://horizon.stellar.org/operations/120453319889080321/effects"
          },
          "succeeds": {
            "href": "https://horizon.stellar.org/effects?order=desc&cursor=120453319889080321"
          },
          "precedes": {
            "href": "https://horizon.stellar.org/effects?order=asc&cursor=120453319889080321"
          }
        },
        "id": "120453319889080321",
        "paging_token": "120453319889080321",
        "transaction_successful": true,
        "source_account": "GB36JPXHJIP34EBRTZ6JVJXL3HEQ65S3CGOID2LKJXBYN2DNLVOFL6FX",
        "type": "payment",
        "type_i": 1,
        "created_at": "2020-02-02T22:41:57Z",
        "transaction_hash": "9995108578bdbd281d298cf91cd3c88725c605018e5e2b896e4dd394d3459d82",
        "asset_type": "native",
        "from": "GB36JPXHJIP34EBRTZ6JVJXL3HEQ65S3CGOID2LKJXBYN2DNLVOFL6FX",
        "to": "GDTLBABZ4NHAXUJAT2HIIQ52UDEBXXZLGB5QILBTCMSKEQENRM6PRIZ5",
        "amount": "68.9999900"
      },
      {
        "_links": {
          "self": {
            "href": "https://horizon.stellar.org/operations/119582730018287617"
          },
          "transaction": {
            "href": "https://horizon.stellar.org/transactions/0a43b067d4ece6f05d4e01f55f616b0108067dd01b93e3a6d651e1ceddcc6d65"
          },
          "effects": {
            "href": "https://horizon.stellar.org/operations/119582730018287617/effects"
          },
          "succeeds": {
            "href": "https://horizon.stellar.org/effects?order=desc&cursor=119582730018287617"
          },
          "precedes": {
            "href": "https://horizon.stellar.org/effects?order=asc&cursor=119582730018287617"
          }
        },
        "id": "119582730018287617",
        "paging_token": "119582730018287617",
        "transaction_successful": true,
        "source_account": "GDTLBABZ4NHAXUJAT2HIIQ52UDEBXXZLGB5QILBTCMSKEQENRM6PRIZ5",
        "type": "path_payment",
        "type_i": 2,
        "created_at": "2020-01-20T14:42:58Z",
        "transaction_hash": "0a43b067d4ece6f05d4e01f55f616b0108067dd01b93e3a6d651e1ceddcc6d65",
        "asset_type": "native",
        "from": "GDTLBABZ4NHAXUJAT2HIIQ52UDEBXXZLGB5QILBTCMSKEQENRM6PRIZ5",
        "to": "GB36JPXHJIP34EBRTZ6JVJXL3HEQ65S3CGOID2LKJXBYN2DNLVOFL6FX",
        "amount": "69.0000000",
        "path": [],
        "source_amount": "69.0000000",
        "source_max": "69.0000000",
        "source_asset_type": "native"
      },
      {
        "_links": {
          "self": {
            "href": "https://horizon.stellar.org/operations/114492553822334977"
          },
          "transaction": {
            "href": "https://horizon.stellar.org/transactions/077804766e707fb6cabf410e0147984614c843cfbef65a69f5089b3c40747cba"
          },
          "effects": {
            "href": "https://horizon.stellar.org/operations/114492553822334977/effects"
          },
          "succeeds": {
            "href": "https://horizon.stellar.org/effects?order=desc&cursor=114492553822334977"
          },
          "precedes": {
            "href": "https://horizon.stellar.org/effects?order=asc&cursor=114492553822334977"
          }
        },
        "id": "114492553822334977",
        "paging_token": "114492553822334977",
        "transaction_successful": true,
        "source_account": "GB36JPXHJIP34EBRTZ6JVJXL3HEQ65S3CGOID2LKJXBYN2DNLVOFL6FX",
        "type": "payment",
        "type_i": 1,
        "created_at": "2019-11-06T04:10:30Z",
        "transaction_hash": "077804766e707fb6cabf410e0147984614c843cfbef65a69f5089b3c40747cba",
        "asset_type": "native",
        "from": "GB36JPXHJIP34EBRTZ6JVJXL3HEQ65S3CGOID2LKJXBYN2DNLVOFL6FX",
        "to": "GDTLBABZ4NHAXUJAT2HIIQ52UDEBXXZLGB5QILBTCMSKEQENRM6PRIZ5",
        "amount": "87.9999900"
      },
      {
        "_links": {
          "self": {
            "href": "https://horizon.stellar.org/operations/114472084008128566"
          },
          "transaction": {
            "href": "https://horizon.stellar.org/transactions/228ff02b7caca055d76c965e9269a2ca3d338d8056b61cd4fab75b62ec0dedea"
          },
          "effects": {
            "href": "https://horizon.stellar.org/operations/114472084008128566/effects"
          },
          "succeeds": {
            "href": "https://horizon.stellar.org/effects?order=desc&cursor=114472084008128566"
          },
          "precedes": {
            "href": "https://horizon.stellar.org/effects?order=asc&cursor=114472084008128566"
          }
        },
        "id": "114472084008128566",
        "paging_token": "114472084008128566",
        "transaction_successful": true,
        "source_account": "GA2TU6C47IBBKYGMSIG5MM3KGIR6LGY2G3TPVO7W3NDY6CEFGR6YJMVT",
        "type": "payment",
        "type_i": 1,
        "created_at": "2019-11-05T20:47:03Z",
        "transaction_hash": "228ff02b7caca055d76c965e9269a2ca3d338d8056b61cd4fab75b62ec0dedea",
        "asset_type": "native",
        "from": "GA2TU6C47IBBKYGMSIG5MM3KGIR6LGY2G3TPVO7W3NDY6CEFGR6YJMVT",
        "to": "GB36JPXHJIP34EBRTZ6JVJXL3HEQ65S3CGOID2LKJXBYN2DNLVOFL6FX",
        "amount": "6.0000000"
      },
      {
        "_links": {
          "self": {
            "href": "https://horizon.stellar.org/operations/114233670373568562"
          },
          "transaction": {
            "href": "https://horizon.stellar.org/transactions/b5faff1b2255be15e490de3701d89959695f9916cb55b35dc42f2c384f4df4af"
          },
          "effects": {
            "href": "https://horizon.stellar.org/operations/114233670373568562/effects"
          },
          "succeeds": {
            "href": "https://horizon.stellar.org/effects?order=desc&cursor=114233670373568562"
          },
          "precedes": {
            "href": "https://horizon.stellar.org/effects?order=asc&cursor=114233670373568562"
          }
        },
        "id": "114233670373568562",
        "paging_token": "114233670373568562",
        "transaction_successful": true,
        "source_account": "GATZCPFWK7MHU7GPUYSY5W63PIRJEMWQQHX3AMLUZPCSLMYGK5HQPBDL",
        "type": "create_account",
        "type_i": 0,
        "created_at": "2019-11-02T07:41:13Z",
        "transaction_hash": "b5faff1b2255be15e490de3701d89959695f9916cb55b35dc42f2c384f4df4af",
        "starting_balance": "83.0000000",
        "funder": "GATZCPFWK7MHU7GPUYSY5W63PIRJEMWQQHX3AMLUZPCSLMYGK5HQPBDL",
        "account": "GB36JPXHJIP34EBRTZ6JVJXL3HEQ65S3CGOID2LKJXBYN2DNLVOFL6FX"
      }
    ]
  }
}
`

**Comment by tyvdh** [comment]
This bug is affecting my ability to access my Tangem card from iOS so would love to see this resolved asap. Thanks!

**Comment by christain-rogobete** [comment]
Hi guys, thank you for sending this issue. We will have a look asap.

**Comment by christain-rogobete** [comment]
Hi, I published a new version 1.7.2. It fixes the parsing problem and extends the result. If you have any further issues pls. let me know.

**Comment by tyvdh** [comment]
@AlexanderOsokin Can you ping me once you've pushed a new version of the Tangem iOS app with this fix and I can confirm if the problem is fixed.

**Comment by AlexanderOsokin** [comment]
@tyvdh Sorry for the long wait. We just pushed a new version with this fix (2.30). Please, try it.

**Comment by tyvdh** [comment]
@AlexanderOsokin Same error

**Comment by tyvdh** [comment]
@AlexanderOsokin Just updated. Same error 😕

![IMG_2673](https://user-images.githubusercontent.com/4383610/76543766-58a27780-645d-11ea-9c7f-90cfa0d4c72a.PNG)

**Comment by AlexanderOsokin** [comment]
@tyvdh You should create an account first by sending >= 1 XLM to this address. We will add a proper error message in the next release

**Comment by tyvdh** [comment]
@AlexanderOsokin Ahhhh. Works! Nice.
