### ISSUE TITLE
How to check TrustLine existing after account opening?

### ISSUE THREAD

**Issue by PavelSakhanko** [Soneso/stellar-ios-mac-sdk#81]
Hi, I need to check trustline state after account opening (exist trustline or not).                                 Are any errors or not?
How to better do this?
Thanks!

**Comment by christain-rogobete** [comment]
Hi Pavel, what do you mean by account opening? You can see if an account has trustlines to other (issuing) accounts by inspecting its balances.

**Comment by PavelSakhanko** [comment]
I use: 
1) StellarSDK().accounts.getAccountDetails(accountId: myAccID) { (response) -> Void in
               I have success response in
switch response {
                case .success(let accountDetails):

2) and then I'm use this for create trustline:

do {
                        let changeTrustOp = ChangeTrustOperation(asset: currency!)
                        let transaction = try Transaction(sourceAccount: accountDetails, operations: [changeTrustOp], memo: Memo.none, timeBounds: nil, maxOperationFee: StellarSettings.maxOperationFee)
                        try transaction.sign(keyPair: sourceAccount, network: network)
                        try StellarSDK().transactions.submitTransaction(transaction: transaction) { (response) -> Void in
                             switch response {
                             case .success:
                                successHandler()
                             case .failure(let error):
                                 StellarSDKLog.printHorizonRequestErrorMessage(tag: "Trust error", horizonRequestError: error)
                                 failHandler()
                             }
                         }
                    } catch {
                        print("New Acc Create Trustline Error")
                    }
If I have 0.0 XLM balance - does this mean that the trustline for the account has been successfully created?
Thanks!

**Comment by christain-rogobete** [comment]
Hi Pavel, 
after trying to add the trust line, if you find a balance entry for the new currency in the account details, then the trustline has been added.
Best 
Christian.

**Comment by christain-rogobete** [comment]
Hi Pavel, can I close this issue?

**Comment by PavelSakhanko** [comment]
Hi! Thanks a lot!
