### ISSUE TITLE
Wrong fee calculation on transaction init from envelope xdr

### ISSUE THREAD

**Issue by shredding** [Soneso/stellar-ios-mac-sdk#83]
Note this [XDR](https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAALR6uVN4RmrfW6K8wdmNznPg6i3Q0dFJTu%2BfC%2FRccUZQAAABkAAN4SkAAAABAAAAAAAAAAAAAAAEAAAAAAAAAAYAAAABRFNRAAAAAABHB84JGCc%2F5%2BR3BOlxDMXPzkRrWjzfWQvocgCZlHVYu3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAAAAAAYAAAABVVNEAAAAAAABxhW5NR6QVXaxvG7fKS5GdaoNNuHlB1wIB%2BSdra3GIn%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAACAAAAAQAAAAIAAAABAAAAAgAAAAAAAAABAAAAADcAko3Ije9aGOP0RkukFkQVJtdyFphVAsp%2FA%2FiOD8%2B7AAAAAQAAAAEAAAAAb0vB44BU2bPolZjPxTq49MypRuzHJ9s9aYwS1QoGvoAAAAABAAAAALR6uVN4RmrfW6K8wdmNznPg6i3Q0dFJTu%2BfC%2FRccUZQAAAAAURTUQAAAAAARwfOCRgnP%2BfkdwTpcQzFz85Ea1o831kL6HIAmZR1WLsAAAAAO5rKAAAAAAAAAAABCga%2BgAAAAEAceq3kjgzL9Hd0ad60WltzntByI1fdBUXp8nmR8V1d5QlEoDcrOHMo73SvpqvW4yfmksM4P4ixS5Pi4VUeboQL&type=TransactionEnvelope&network=test) ...

It has four transactions and wants to pay a fee of 400. It has a valid signature of the account sending the payment (the fourth transaction).

After running this code:

```
let transaction = try Transaction(envelopeXdr: xdr): 
let keyPair = try KeyPair.init(secretSeed: secret)
try transaction.sign(keyPair: keyPair, network: network)
print(transaction.encodedEnvelope())
```

The transcation becomes [this](https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAALR6uVN4RmrfW6K8wdmNznPg6i3Q0dFJTu%2BfC%2FRccUZQAAAGQAAN4SkAAAABAAAAAAAAAAAAAAAEAAAAAAAAAAYAAAABRFNRAAAAAABHB84JGCc%2F5%2BR3BOlxDMXPzkRrWjzfWQvocgCZlHVYu3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAAAAAAYAAAABVVNEAAAAAAABxhW5NR6QVXaxvG7fKS5GdaoNNuHlB1wIB%2BSdra3GIn%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAACAAAAAQAAAAIAAAABAAAAAgAAAAAAAAABAAAAADcAko3Ije9aGOP0RkukFkQVJtdyFphVAsp%2FA%2FiOD8%2B7AAAAAQAAAAEAAAAAb0vB44BU2bPolZjPxTq49MypRuzHJ9s9aYwS1QoGvoAAAAABAAAAALR6uVN4RmrfW6K8wdmNznPg6i3Q0dFJTu%2BfC%2FRccUZQAAAAAURTUQAAAAAARwfOCRgnP%2BfkdwTpcQzFz85Ea1o831kL6HIAmZR1WLsAAAAAO5rKAAAAAAAAAAACCga%2BgAAAAEAceq3kjgzL9Hd0ad60WltzntByI1fdBUXp8nmR8V1d5QlEoDcrOHMo73SvpqvW4yfmksM4P4ixS5Pi4VUeboQLXHFGUAAAAEDKIgGqCTZzl4CrKFCi%2BhCMdGgKZpKVW3UCbhGVJ%2Fmx%2BaEGIJw70%2FsZ3eQsT7UuGyGbNtvFsS1YxpUwtu%2Bx31wG&type=TransactionEnvelope&network=test). 

Note that the fee has been scaled by a factor of four due to [this line](https://github.com/Soneso/stellar-ios-mac-sdk/blob/8efe9ea5bb69d3b2c2c27a54418c47f2f8ca426f/stellarsdk/stellarsdk/sdk/Transaction.swift#L46) (the xdr has four transactions). This is problematic, not only because the fee has changed, but more importantly because the given signature is no longer valid. Essentially this prohibits co-signing functionality.

Secret Key to reproduce: `SA33GXHR62NBMBH5OZK5JHXR3X7KAANKMVXPIP6VQQO6N5HGKFB66HWR`

**Comment by christain-rogobete** [comment]
Hi Christian,

thank you for finding that problem and for adding this issue. I fixed it and released a new version of the sdk (1.7.3). Please let me know if the fix works for you.

Best
Christian R.

**Comment by shredding** [comment]
That was super fast! I'll check in the evening.

**Comment by shredding** [comment]
This does work for me. 

However, in the event of a [surge pricing](https://www.stellar.org/developers/guides/concepts/fees.html#surge-pricing) someone could potentially come up with a fee like in this case 403, which is not divisible by the # of transactions.
Since I'm not a swift developer

**Comment by shredding** [comment]
Closing that for now, works atm
