### ISSUE TITLE
Error 6 after submitting Transaction

### ISSUE THREAD

**Issue by mdolmatovich** [Soneso/stellar-ios-mac-sdk#87]
After submitting Transaction, I always get Error 6 when decoding transaction

in file SubmitTransactionResponse.swift
```
public required init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        transactionHash = try values.decode(String.self, forKey: .transactionHash)
        ledger = try values.decode(Int.self, forKey: .ledger)
        
        let encodedEnvelope = try values.decode(String.self, forKey: .envelopeXDR)
        let data = Data(base64Encoded: encodedEnvelope)!
        transactionEnvelope = try XDRDecoder.decode(TransactionEnvelopeXDR.self, data:data)
        
        let encodedResult = try values.decode(String.self, forKey: .transactionResult)
        let resultData = Data(base64Encoded: encodedResult)!
        transactionResult = try XDRDecoder.decode(TransactionResultXDR.self, data:resultData)
        
        let encodedMeta = try values.decode(String.self, forKey: .transactionMeta)
        let metaData = Data(base64Encoded: encodedMeta)!
        transactionMeta = try XDRDecoder.decode(TransactionMetaXDR.self, data:metaData)
    }
```

**Comment by shredding** [comment]
I get an `error 11` - worked before as well.

**Comment by christain-rogobete** [comment]
Hi @mdolmatovich , first of all thank you for reporting the issue. I think it is related to this issue: https://github.com/Soneso/stellar-ios-mac-sdk/issues/86
I plan on taking care of it next week. I'll keep you posted.

**Comment by christain-rogobete** [comment]
In the meantime you can continue to use the main net, it will use protocol 12 for about another month.

**Comment by shredding** [comment]
@christain-rogobete do you think that's related to my error as well? It's happening on the testnet only.

**Comment by christain-rogobete** [comment]
Hi @shredding, yes, I think so. Let's see if the errors persist after addressing the protocol 13 issue.

**Comment by christian-rogobete** [comment]
Hi @mdolmatovich and @shredding , then new version 1.8.0 is now available. See releases: https://github.com/Soneso/stellar-ios-mac-sdk/releases
Please let me know if the issues still occur with the new version

**Comment by shredding** [comment]
It's not on cocoa yet, isn't it? https://cocoapods.org/pods/stellar-ios-mac-sdk

**Comment by christian-rogobete** [comment]
Hi @shredding 

I published it yesterday

<img width="590" alt="Screenshot 2020-05-18 at 16 30 03" src="https://user-images.githubusercontent.com/35729606/82230563-282efc00-992c-11ea-9e57-f6f677e747cf.png">

and in my project it seams to load:

<img width="635" alt="Screenshot 2020-05-18 at 17 20 06" src="https://user-images.githubusercontent.com/35729606/82230589-354beb00-992c-11ea-8050-ff02c573b20e.png">

What is it complaining about on your side?

**Comment by mdolmatovich** [comment]
Hi @christian-rogobete christian-rogobete
The issue with Error 6 was solved. Thank you
But now I have error 2 when call getAccountDetails (in file AccountService) it returns Error 2, but account is authorized. Can it be connected with this issue?

**Comment by christian-rogobete** [comment]
Hi @mdolmatovich, thank you for your message. Can you pls. send me the accountID, I will try to reproduce your error and let you know.

**Comment by mdolmatovich** [comment]
> Hi @mdolmatovich, thank you for your message. Can you pls. send me the accountID, I will try to reproduce your error and let you know.

GCDP5EESKZQM7UWQTTNVNAYYBUPK2AGR6OVPLB3OICUZO5WQKYZ66DZD

**Comment by christian-rogobete** [comment]
Hi @mdolmatovich , I think it has nothing to do with the SDK. At least it works for me:

<img width="974" alt="Screenshot 2020-05-19 at 16 37 45" src="https://user-images.githubusercontent.com/35729606/82340193-3abe3980-99ef-11ea-954e-e1d1c44cd283.png">

If you like to share your code, I can have a look.

**Comment by AndroidVironitDeveloper** [comment]
@christian-rogobete Hi! I'm working with @mdolmatovich.
Could you explain us how to set unique horizon url for Stellar on IOS?
We have Stellar url https://stellar-test.bdnodes.net/?auth=uO************.
But if we try to submit transaction using this url we got unauthorized token error.
I looked through the SDK and found out that in file ServiceHelper.swift the path for network request is just added to base url like this: **https://stellar-test.bdnodes.net/?auth=uO************/transactions.**
When it should be: **https://stellar-test.bdnodes.net/transactions?auth=uO************.

**Comment by christian-rogobete** [comment]
Hi @AndroidVironitDeveloper, thank you for writing. Can you please open a new issue for this topic so that we don't mix up the topics and also help others who may search for issues and their solutions.
