### ISSUE TITLE
Using unique url with query parameter

### ISSUE THREAD

**Issue by AndroidVironitDeveloper** [Soneso/stellar-ios-mac-sdk#88]
We have Stellar url https://stellar-test.bdnodes.net/?auth=uO************.
But if we try to submit transaction using this url we got unauthorized token error.
I looked through the SDK and found out that in file ServiceHelper.swift the path for network request is just added to base url like this: https://stellar-test.bdnodes.net/?auth=uO************/transactions.
When it should be: https://stellar-test.bdnodes.net/transactions?auth=uO**********.

Here is error response when we tried to submit the transaction using our unique url:
<NSHTTPURLResponse: 0x7fd373060270> { URL: https://stellar-test.bdnodes.net/?auth=uO**************/transactions } { Status Code: 401, Headers {
"Access-Control-Allow-Origin" = (
"*"
);
"Content-Length" = (
29
);
"Content-Type" = (
"text/plain; charset=utf-8"
);
Date = (
"Wed, 20 May 2020 12:42:35 GMT"
);
Server = (
"nginx/1.18.0"
);
"x-content-type-options" = (
nosniff
);
} }

**Comment by christian-rogobete** [comment]
Hi @AndroidVironitDeveloper, thank you for reporting this issue. You are right, with the current version of the SDK it is not possible to achieve the result you described. It only works with urls that have no parameters. I will think about a future solution and let you know.

**Comment by christian-rogobete** [comment]
Hi @AndroidVironitDeveloper, I will address your requirement. I will construct the urls by decoding the passed base url string, append the desired path to the path field, and then re-encoding the url.

**Comment by AndroidVironitDeveloper** [comment]
Hi @christian-rogobete. Glad to hear. Looking forward for new build.

**Comment by christian-rogobete** [comment]
Hi @AndroidVironitDeveloper, the new release 1.8.1:
https://github.com/Soneso/stellar-ios-mac-sdk/releases/tag/1.8.1 
adds support for query parameters. 
Pls. let me know if it works for you now

**Comment by AndroidVironitDeveloper** [comment]
@christian-rogobete Thanks! We will check and give you feedback as soon as possible

**Comment by AndroidVironitDeveloper** [comment]
@christian-rogobete It works great! Thanks!

**Comment by christian-rogobete** [comment]
@AndroidVironitDeveloper great! Thank you for the fast testing.
