### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by onnz** [Soneso/stellar-ios-mac-sdk#9]
I added your SDK to my project and it build successfully but when add the code 

    @IBAction func AA(_ sender: Any) {
        
        let keyPair = try! KeyPair.generateRandomKeyPair()
        publicKeyText.text = keyPair.accountId
        privateKeyText.text = keyPair.secretSeed
    }

It show the error that
dyld: Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib
  Referenced from: /Users/onnz/Library/Developer/Xcode/DerivedData/AAApple-dpiwihmukivykxecjcqukwbxnjxo/Build/Products/Debug-iphonesimulator/stellarsdk.framework/stellarsdk
  Reason: image not found
(lldb)

**Comment by chelemen-razvan** [comment]
Please make sure you follow all the steps in embedding a framework https://developer.apple.com/library/content/technotes/tn2435/_index.html

**Comment by onnz** [comment]
The answer solved my problem, It need to add stellarsdk to "Embedded Binariess" in the general tap of project
