### ISSUE TITLE
Multiple signing problems v1.8.2

### ISSUE THREAD

**Issue by let-it-snow** [Soneso/stellar-ios-mac-sdk#91]
Hi Christian! 
We probably discovered two signing problems. It seems that we have the same problems as issue #89 only for signing transaction v1 and for signing transaction v0 with more than one operation.

**First problem:**

I assume there is the signing problem of v1 transactions. You can check this test case for a better understanding:

```
func testTransactionV1Sign() throws {
    let keyPair = try! KeyPair(secretSeed: "SB2VUAO2O2GLVUQOY46ZDAF3SGWXOKTY27FYWGZCSV26S24VZ6TUKHGE")
    // transaction envelope v1
    let xdr = "AAAAAgAAAADUtWEQOb8u8wqHpML1OV4SV3E5EjliNElgRW2AmJDkaQAAJxAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAEAAAAA1LVhEDm/LvMKh6TC9TleEldxORI5YjRJYEVtgJiQ5GkAAAABAAAAANS1YRA5vy7zCoekwvU5XhJXcTkSOWI0SWBFbYCYkORpAAAAAAAAAAAAAAABAAAAAAAAAAA="

    let envelopeXDR = try! TransactionEnvelopeXDR(xdr: xdr)
    let txHash = try! [UInt8](envelopeXDR.txHash(network: .public))
    envelopeXDR.appendSignature(signature: keyPair.signDecorated(txHash))
      
    let userSignature = envelopeXDR.txSignatures.first!.signature.base64EncodedString()
    let validUserSignature = "1iw8QognbB+8DmvUTAk0SQSxjpsYqa2pnP9/A7qJwyJ5IPVG+wl4w6M5mHel5CjzsnWKwurE/LCY26Jmz5KiBw=="
        
    print("XDR Envelope: \(envelopeXDR.xdrEncoded!)")
    XCTAssertEqual(validUserSignature, userSignature)
  }
```

After signing signatures are not equal. This XDR transaction was signed with the help of Stellar Laboratory: [link](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAADUtWEQOb8u8wqHpML1OV4SV3E5EjliNElgRW2AmJDkaQAAJxAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAEAAAAA1LVhEDm%2FLvMKh6TC9TleEldxORI5YjRJYEVtgJiQ5GkAAAABAAAAANS1YRA5vy7zCoekwvU5XhJXcTkSOWI0SWBFbYCYkORpAAAAAAAAAAAAAAABAAAAAAAAAAGYkORpAAAAQNYsPEKIJ2wfvA5r1EwJNEkEsY6bGKmtqZz%2FfwO6icMieSD1RvsJeMOjOZh3peQo87J1isLqxPywmNuiZs%2BSogc%3D&type=TransactionEnvelope&network=public)

And this transaction after signing Stellar iOS SDK: [link](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAADUtWEQOb8u8wqHpML1OV4SV3E5EjliNElgRW2AmJDkaQAAJxAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAEAAAAA1LVhEDm%2FLvMKh6TC9TleEldxORI5YjRJYEVtgJiQ5GkAAAABAAAAANS1YRA5vy7zCoekwvU5XhJXcTkSOWI0SWBFbYCYkORpAAAAAAAAAAAAAAABAAAAAAAAAAGYkORpAAAAQBS%2B1AaF7a84e01M72kZSnSyjyQ%2BOo6OzRRHFDESpKoP2ljrfK3%2F8HLoXxdDvxA8NY2dbpepn14vExHOzjP8Yw8%3D&type=TransactionEnvelope&network=public)

**Second problem:**

The same problem, the signature isn't valid after signing v0 transaction with more than one operation.

Test case for a better understanding:
```
func testTransactionV0SignWithTwoOperations() throws {
    let keyPair = try! KeyPair(secretSeed: "SB2VUAO2O2GLVUQOY46ZDAF3SGWXOKTY27FYWGZCSV26S24VZ6TUKHGE")
    // transaction envelope v0 with two payment operations
    let xdr = "AAAAANS1YRA5vy7zCoekwvU5XhJXcTkSOWI0SWBFbYCYkORpAAAAyAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAABAAAAAE8LpHirFqhklgFS3bqZmOEvg53t/uQ8CFrefQom/uZVAAAAAAAAAAAF9eEAAAAAAAAAAAEAAAAATwukeKsWqGSWAVLdupmY4S+Dne3+5DwIWt59Cib+5lUAAAAAAAAAAAL68IAAAAAAAAAAAA=="
    
    let envelopeXDR = try! TransactionEnvelopeXDR(xdr: xdr)
    let txHash = try! [UInt8](envelopeXDR.txHash(network: .public))
    envelopeXDR.appendSignature(signature: keyPair.signDecorated(txHash))
      
    let userSignature = envelopeXDR.txSignatures.first!.signature.base64EncodedString()
    let validUserSignature = "/x+ipnunmfDID9kX09bmnZOLSG/3Cwld0zgHzpgN6vNAQ4ebrcnALv8hwvVlS5IFY6wKRacWBM0gA9eSd68/CQ=="
        
    print("XDR Envelope: \(envelopeXDR.xdrEncoded!)")
    XCTAssertEqual(validUserSignature, userSignature)
  }
```
After signing signatures are not equal. This XDR transaction was signed with the help of Stellar Laboratory: [link](https://laboratory.stellar.org/#xdr-viewer?input=AAAAANS1YRA5vy7zCoekwvU5XhJXcTkSOWI0SWBFbYCYkORpAAAAyAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAABAAAAAE8LpHirFqhklgFS3bqZmOEvg53t%2FuQ8CFrefQom%2FuZVAAAAAAAAAAAF9eEAAAAAAAAAAAEAAAAATwukeKsWqGSWAVLdupmY4S%2BDne3%2B5DwIWt59Cib%2B5lUAAAAAAAAAAAL68IAAAAAAAAAAAZiQ5GkAAABA%2Fx%2BipnunmfDID9kX09bmnZOLSG%2F3Cwld0zgHzpgN6vNAQ4ebrcnALv8hwvVlS5IFY6wKRacWBM0gA9eSd68%2FCQ%3D%3D&type=TransactionEnvelope&network=public)
And this transaction after signing Stellar iOS SDK: [link](https://laboratory.stellar.org/#xdr-viewer?input=AAAAANS1YRA5vy7zCoekwvU5XhJXcTkSOWI0SWBFbYCYkORpAAAAyAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAABAAAAAE8LpHirFqhklgFS3bqZmOEvg53t%2FuQ8CFrefQom%2FuZVAAAAAAAAAAAF9eEAAAAAAAAAAAEAAAAATwukeKsWqGSWAVLdupmY4S%2BDne3%2B5DwIWt59Cib%2B5lUAAAAAAAAAAAL68IAAAAAAAAAAAZiQ5GkAAABAdvIsw3IK0D8TEMcqYM2DiRb%2B16NIsWpRKPclYBhizdzsGKwv43QxmjAczMR04Odt%2FxxdyElU1y2XoTlawkBMDQ%3D%3D&type=TransactionEnvelope&network=public)

**Comment by christian-rogobete** [comment]
Hello @let-it-snow,

thank you for adding this issue. There is a new version prepared, that will be released tomorrow as soon as the main net will switch to protocol 13. The code is already committed to this repo. The new version will **remove** support for signing and submitting v0 transactions directly. 

However, I tested your two examples with the new version and the first one is working without any problems:

<img width="1051" alt="Screenshot 2020-06-17 at 17 11 37" src="https://user-images.githubusercontent.com/35729606/84916482-6d2a8780-b0be-11ea-9a2b-2205f3852554.png">

If you want to test that with version 1.8.2 than pls. provide the protocol 13 flag as described in issue #89 

Your second example will still work with the new version if you are going to use this code:

```swift
let transaction = try! Transaction(envelopeXdr: xdr)
try! transaction.sign(keyPair: keyPair, network: .public)
let envelopeXDR = try! TransactionEnvelopeXDR(xdr: transaction.encodedEnvelope())
```
instead of your code:
```swift
let envelopeXDR = try! TransactionEnvelopeXDR(xdr: xdr)
let txHash = try! [UInt8](envelopeXDR.txHash(network: .public))
envelopeXDR.appendSignature(signature: keyPair.signDecorated(txHash))
```
This is because the v0 transaction will be transformed to a v1 transaction when creating the envelope.

<img width="1045" alt="Screenshot 2020-06-17 at 17 12 06" src="https://user-images.githubusercontent.com/35729606/84917249-5d5f7300-b0bf-11ea-9306-12097e8bcc14.png">

You can do the same for your first case (replace your code as shown above). By doing that you will not need to differentiate between the 2 cases:

<img width="1044" alt="Screenshot 2020-06-17 at 17 13 31" src="https://user-images.githubusercontent.com/35729606/84917381-8a138a80-b0bf-11ea-9faf-c1de31c5ed73.png">

Please let me know if you need any further help.

**Comment by let-it-snow** [comment]
Thank you for your reply. 
I'm glad that the first case will be work with the new version.
But I still have a problem with the second case. Unfortunately, I can't use your example in my situation, because I don't have access to the secret key. I can only pass the hash of the transaction and get a signature after that. So I need to have the possibility to insert a signature to an envelope manually.
And as I understand correctly at the beginning, we will use both types of transactions (v0 and v1), even after switching to protocol 13 today. So it will be great if we can support two transaction types.

**Comment by christian-rogobete** [comment]
Hi @let-it-snow,

I am not sure that I understand your problem, but you can always transform an v0 transaction envelope into a v1 transaction envelope.

<img width="905" alt="Screenshot 2020-06-18 at 13 08 48" src="https://user-images.githubusercontent.com/35729606/85013563-13c96380-b165-11ea-9ffa-677fd952ffb7.png">

Here is the code:

```swift
var envelopeXDR = try! TransactionEnvelopeXDR(xdr: xdr)
switch envelopeXDR {
case .v0(let txEnvV0):
  // if its a v0 transaction envelope, convert it to a v1 transaction envelope
  let tV0Xdr = txEnvV0.tx
  let pk = try PublicKey(tV0Xdr.sourceAccountEd25519)
  let transactionXdr = TransactionXDR(sourceAccount: pk, seqNum: tV0Xdr.seqNum, timeBounds: tV0Xdr.timeBounds, memo: tV0Xdr.memo, operations: tV0Xdr.operations, maxOperationFee: tV0Xdr.fee / UInt32(tV0Xdr.operations.count) )
  let txV1E = TransactionV1EnvelopeXDR(tx: transactionXdr, signatures: envelopeXDR.txSignatures)
  envelopeXDR = TransactionEnvelopeXDR.v1(txV1E)
default:
  break
}
let txHash = try! [UInt8](envelopeXDR.txHash(network: .public))
envelopeXDR.appendSignature(signature: keyPair.signDecorated(txHash))
```

Hop this helps. Let me know.

**Comment by let-it-snow** [comment]
Hi @christian-rogobete,
Yes, this helped, thanks. Waiting for a new release.
