### ISSUE TITLE
Response failed to parse, but transaction passed successfully

### ISSUE THREAD

**Issue by AlexanderOsokin** [Soneso/stellar-ios-mac-sdk#92]
stellar-ios-mac-sdk 1.7.4 produced the error:
"The operation couldn’t be completed. (stellarsdk.XDRDecoder.Error error 6.)"

The response causes the error:

"{\n  \"memo\": \"\",\n  \"memo_bytes\": \"\",\n  \"_links\": {\n    \"self\": {\n      \"href\": \"https://horizon.stellar.org/transactions/5cb61b48b461261a0c75f063223a83032cae488020ecb67abd6f1c12e6881ed6\"\n    },\n    \"account\": {\n      \"href\": \"https://horizon.stellar.org/accounts/GCAVFHNT6U4T3GHFDZNLA7K6C2COAXOZQYJSC4BCBWH7UGZ6EXWZFWT7\"\n    },\n    \"ledger\": {\n      \"href\": \"https://horizon.stellar.org/ledgers/30206509\"\n    },\n    \"operations\": {\n      \"href\": \"https://horizon.stellar.org/transactions/5cb61b48b461261a0c75f063223a83032cae488020ecb67abd6f1c12e6881ed6/operations{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"effects\": {\n      \"href\": \"https://horizon.stellar.org/transactions/5cb61b48b461261a0c75f063223a83032cae488020ecb67abd6f1c12e6881ed6/effects{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"precedes\": {\n      \"href\": \"https://horizon.stellar.org/transactions?order=asc\\u0026cursor=129735968281411584\"\n    },\n    \"succeeds\": {\n      \"href\": \"https://horizon.stellar.org/transactions?order=desc\\u0026cursor=129735968281411584\"\n    },\n    \"transaction\": {\n      \"href\": \"https://horizon.stellar.org/transactions/5cb61b48b461261a0c75f063223a83032cae488020ecb67abd6f1c12e6881ed6\"\n    }\n  },\n  \"id\": \"5cb61b48b461261a0c75f063223a83032cae488020ecb67abd6f1c12e6881ed6\",\n  \"paging_token\": \"129735968281411584\",\n  \"successful\": true,\n  \"hash\": \"5cb61b48b461261a0c75f063223a83032cae488020ecb67abd6f1c12e6881ed6\",\n  \"ledger\": 30206509,\n  \"created_at\": \"2020-06-19T14:47:36Z\",\n  \"source_account\": \"GCAVFHNT6U4T3GHFDZNLA7K6C2COAXOZQYJSC4BCBWH7UGZ6EXWZFWT7\",\n  \"source_account_sequence\": \"114986775708958727\",\n  \"fee_account\": \"GCAVFHNT6U4T3GHFDZNLA7K6C2COAXOZQYJSC4BCBWH7UGZ6EXWZFWT7\",\n  \"fee_charged\": \"100\",\n  \"max_fee\": \"100\",\n  \"operation_count\": 1,\n  \"envelope_xdr\": \"AAAAAgAAAACBUp2z9Tk9mOUeWrB9XhaE4F3ZhhMhcCINj/obPiXtkgAAAGQBmIPdAAAABwAAAAEAAAAAXuzPxgAAAABe7NA+AAAAAQAAAAAAAAABAAAAAAAAAAEAAAAABxZMjVn7EZHj/IE6WtYAdrWQGUy0lzZ3jf3+/YQJ6hgAAAAAAAAAAAAB4LoAAAAAAAAAAT4l7ZIAAABA2ubcS9/WuT4WZHnehpufaqjleIdXpcNGMRltpv2b7HFpw3lTZvLylcW6rIFH9iI3Am1/Q2scM+Nd7RtWoRv4AA==\",\n  \"result_xdr\": \"AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAA=\",\n  \"result_meta_xdr\": \"AAAAAgAAAAIAAAADAczqLQAAAAAAAAAAgVKds/U5PZjlHlqwfV4WhOBd2YYTIXAiDY/6Gz4l7ZIAAAAAAJp3OgGYg90AAAAGAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAczqLQAAAAAAAAAAgVKds/U5PZjlHlqwfV4WhOBd2YYTIXAiDY/6Gz4l7ZIAAAAAAJp3OgGYg90AAAAHAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAAABAAAAAMBzOoLAAAAAAAAAAAHFkyNWfsRkeP8gTpa1gB2tZAZTLSXNneN/f79hAnqGAAAAAAAmJaAAZiD8QAAAA0AAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEBzOotAAAAAAAAAAAHFkyNWfsRkeP8gTpa1gB2tZAZTLSXNneN/f79hAnqGAAAAAAAmnc6AZiD8QAAAA0AAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAMBzOotAAAAAAAAAACBUp2z9Tk9mOUeWrB9XhaE4F3ZhhMhcCINj/obPiXtkgAAAAAAmnc6AZiD3QAAAAcAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEBzOotAAAAAAAAAACBUp2z9Tk9mOUeWrB9XhaE4F3ZhhMhcCINj/obPiXtkgAAAAAAmJaAAZiD3QAAAAcAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAA=\",\n  \"fee_meta_xdr\": \"AAAAAgAAAAMBzOoLAAAAAAAAAACBUp2z9Tk9mOUeWrB9XhaE4F3ZhhMhcCINj/obPiXtkgAAAAAAmneeAZiD3QAAAAYAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEBzOotAAAAAAAAAACBUp2z9Tk9mOUeWrB9XhaE4F3ZhhMhcCINj/obPiXtkgAAAAAAmnc6AZiD3QAAAAYAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA==\",\n  \"memo_type\": \"text\",\n  \"signatures\": [\n    \"2ubcS9/WuT4WZHnehpufaqjleIdXpcNGMRltpv2b7HFpw3lTZvLylcW6rIFH9iI3Am1/Q2scM+Nd7RtWoRv4AA==\"\n  ],\n  \"valid_after\": \"2020-06-19T14:46:30Z\",\n  \"valid_before\": \"2020-06-19T14:48:30Z\"\n}"

**Comment by christian-rogobete** [comment]
Hi @AlexanderOsokin, the sdk version 1.7.4 is old and does not support the new stellar core protocol 13 that has been released to the test and to the main net. Please update to the sdk to the latest version.

**Comment by AlexanderOsokin** [comment]
Thank you!
